Repository argoproj/argo-cd, pull requests merged in 2019-11, with the labels that each got.

#2716 Make directory enforcer more lenient and add flag
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  util/helm/cmd.go
  util/helm/cmd_test.go
  util/security/path_traversal.go
  util/security/path_traversal_test.go
  util/settings/settings.go
Labels: S, bug

#2766 Update README.md to add KubeCon workshop
  README.md
Labels: S

#2760 Ensures that Helm charts are correctly resolved before sync. Fixes #2758
  server/application/application.go
  server/application/application_test.go
  util/helm/client.go
Labels: M, bug
