Repository argoproj/argo-cd, pull requests merged in 2021-02, with the labels that each got.

#5259 fix(ui): Overlapping buttons at narrow screen widths
  ui/src/app/applications/components/application-details/application-details.scss
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-pod-view/pod-view.scss
  ui/src/app/applications/components/application-status-panel/application-status-panel.scss
Labels: only-needs-a-rubber-stamp

#5419 fix(ui): Add header and browser title to fullscreen logs viewer
  ui/src/app/applications/components/application-fullscreen-logs/application-fullscreen-logs.tsx
Labels: only-needs-a-rubber-stamp

#5417 feat: add source repos to fields inherited from global projects
  docs/user-guide/projects.md
  util/argo/argo.go
Labels: only-needs-a-rubber-stamp

#5496 chore: Add reminder to PR template to link auto close issue
  .github/pull_request_template.md
Labels: only-needs-a-rubber-stamp

#5476 fix: add the missing rbac resources to the documentation
  docs/operator-manual/rbac.md
Labels: cherry-pick/1.8

#5534 docs: Fix dead link in documentation for GitHub SSO integration
  docs/operator-manual/user-management/index.md
Labels: cherry-pick/1.8

#5511 fix: 'argocd app wait --suspended' stuck if operation is in progress
  cmd/argocd/commands/app.go
  test/e2e/app_management_test.go
  test/e2e/sync_waves_test.go
  test/e2e/testdata/sync-waves/cm-1.yaml
  test/e2e/testdata/sync-waves/cm-2.yaml
  test/e2e/testdata/sync-waves/pod-1.yaml
  test/e2e/testdata/sync-waves/pod-2.yaml
Labels: cherry-pick/1.8

#5583 fix: updated retry var type from string to duration for app sync
  cmd/argocd/commands/app.go
  docs/operator-manual/upgrading/1.8-1.9.md
  docs/user-guide/commands/argocd_app_sync.md
Labels: breaking/low

#5617 fix: API server should not print resource body when resource update fails
  server/application/application.go
  test/e2e/app_management_test.go
Labels: cherry-pick/1.6, cherry-pick/1.7, cherry-pick/1.8
