Repository argoproj/argo-cd, pull requests merged in 2021-08, with the labels that each got.

#6886 fix: make sure orphaned filter checkbox is clickable
  ui/src/app/applications/components/application-details/application-details.scss
Labels: cherry-pick/2.1, needs-verification

#6905 docs: Add replace description on individual resource level
  docs/user-guide/sync-options.md
Labels: cherry-pick/2.1, type:docs

#6615 docs: Update contributor docs
  docs/CONTRIBUTING.md
  docs/developer-guide/code-contributions.md
  docs/developer-guide/contributing.md
  docs/developer-guide/running-locally.md
  docs/developer-guide/toolchain-guide.md
  mkdocs.yml
Labels: cherry-pick/2.1

#6967 fix: rollout v1.0 'Paused' status.phase should map to Argo CD 'Suspended'
  resource_customizations/argoproj.io/Rollout/health.lua
  resource_customizations/argoproj.io/Rollout/health_test.yaml
  resource_customizations/argoproj.io/Rollout/testdata/suspended_v1.0_pausedRollout.yaml
Labels: cherry-pick/2.1

#6987 Fix: Disable generating of Root CA Certificates when Auto Generating Self Signed Certs.
  util/settings/settings.go
  util/tls/tls.go
Labels: security, cherry-pick/2.1

#7025 fix(ui): Resource details crashed due to extensions
  ui/src/app/applications/components/resource-details/resource-details.tsx
Labels: cherry-pick/2.1

#7045 fix(ui): Add State to props passed to Extensions
  ui/src/app/applications/components/resource-details/resource-details.tsx
  ui/src/app/shared/services/extensions-service.ts
Labels: cherry-pick/2.1
