Repository argoproj/argo-cd, pull requests merged in 2021-05, with the labels that each got.

#6142 chore: Update haproxy for redis-ha to 2.0.22
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: cherry-pick/1.8, cherry-pick/2.0, security

#6253 fix: Enable kex algo diffie-hellman-group-exchange-sha256 for go-git ssh
  test/fixture/testrepos/Procfile
  util/git/client.go
  util/git/ssh.go
Labels: cherry-pick/2.0

#6259 fix(ui): Don't count errored or completed neighbor pods toward resource consumption
  controller/appcontroller.go
  controller/cache/cache.go
  controller/cache/info.go
Labels: cherry-pick/2.0

#5893 chore: Organize Application-related defaults/constants in the Application API's package.
  cmd/argocd-util/commands/app.go
  cmd/argocd-util/commands/app_test.go
  cmd/argocd-util/commands/cluster.go
  cmd/argocd/commands/app.go
  cmd/argocd/commands/cluster.go
  cmd/util/app.go
  common/common.go
  controller/appcontroller.go
  controller/appcontroller_test.go
  controller/cache/cache.go
  pkg/apis/application/v1alpha1/app_project_types.go
  pkg/apis/application/v1alpha1/application_annotations.go
  pkg/apis/application/v1alpha1/application_defaults.go
  pkg/apis/application/v1alpha1/cluster_constants.go
  pkg/apis/application/v1alpha1/repository_types.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
  server/application/application.go
  server/project/project.go
  server/server.go
  server/server_test.go
  test/e2e/app_management_test.go
  test/e2e/fixture/app/context.go
  test/e2e/project_management_test.go
  util/argo/argo.go
  util/db/cluster.go
  util/db/cluster_norace_test.go
  util/db/cluster_test.go
  util/webhook/webhook.go
  util/webhook/webhook_test.go
Labels: breaking/low

#6319 fix: grpc web proxy must ensure to read full header
  pkg/apiclient/grpcproxy.go
Labels: cherry-pick/2.0

#6320 fix: add missing --container flag to 'argocd app logs' command
  cmd/argocd/commands/app.go
  docs/user-guide/commands/argocd_app_logs.md
Labels: cherry-pick/2.0

#6358 chore: Update Golang to v1.16.4
  .github/workflows/image.yaml
  .github/workflows/release.yaml
  Dockerfile
  test/container/Dockerfile
Labels: cherry-pick/2.0
