Repository argoproj/argo-cd, pull requests merged in 2021-07, with the labels that each got.

#6627 fix: download Pod Logs button not honouring argocd-server rootpath (#6548)
  ui/src/app/shared/services/applications-service.ts
Labels: cherry-pick/2.0

#6458 fix: add insecure-skip-tls-verify on helm pull when Creds.InsecureSkipVerify is set to true
  util/helm/client_test.go
  util/helm/cmd.go
Labels: needs-verification

#6800 fix: Webhook does not trigger refresh when using target revision format refs/heads/<branch name>
  util/webhook/webhook.go
  util/webhook/webhook_test.go
Labels: cherry-pick/2.0

#6380 feat: update rollout health check for Argo Rollouts v1.0
  resource_customizations/argoproj.io/Rollout/health.lua
  resource_customizations/argoproj.io/Rollout/health_test.yaml
  resource_customizations/argoproj.io/Rollout/testdata/degraded_statusPhaseMessage.yaml
  resource_customizations/argoproj.io/Rollout/testdata/healthy_legacy_v1.0_newWorkloadGeneration.yaml
  resource_customizations/argoproj.io/Rollout/testdata/healthy_newWorkloadGeneration.yaml
  resource_customizations/argoproj.io/Rollout/testdata/progressing_newWorkloadGeneration.yaml
Labels: cherry-pick/2.0

#6845 Fixes #6844 multiple global projects can be configured
  util/argo/argo.go
  util/argo/argo_test.go
Labels: cherry-pick/2.1

#6854 fix: include cluster level RBAC into argocd-core manifests
  manifests/core-install.yaml
  manifests/core-install/kustomization.yaml
Labels: needs-verification

#6852 fix: util.cli.SetLogLevel should update global log level
  util/cli/cli.go
Labels: needs-verification
