Repository argoproj/argo-cd, pull requests merged in 2021-09, with the labels that each got.

#7164 feat: ability to switch user during test execution
  test/e2e/accounts_test.go
  test/e2e/fixture/account/actions.go
  test/e2e/fixture/account/consequences.go
  test/e2e/fixture/account/context.go
  test/e2e/fixture/fixture.go
Labels: enhancement, component:test

#7162 #7144 fix: add custom volume as Helm working dir
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.1

#7166 fix: use selected helm-values #7099
  reposerver/repository/repository.go
Labels: cherry-pick/2.1

#7187 feat: Ability to test rbac and implement it with scoped repos
  assets/swagger.json
  cmd/argocd/commands/repo.go
  pkg/apiclient/repository/repository.pb.go
  server/repository/repository.go
  server/repository/repository.proto
  test/e2e/fixture/account/actions.go
  test/e2e/fixture/fixture.go
  test/e2e/fixture/project/context.go
  test/e2e/scoped_repository_test.go
Labels: enhancement, component:test

#7194 chore: Update haproxy for redis-ha to 2.0.25
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: security, cherry-pick/2.0, cherry-pick/2.1

#7206 Scoped resources doc
  docs/user-guide/projects.md
Labels: documentation

#7224 feat: show difference in repos that exist and that should be changed
  go.mod
  go.sum
  server/application/application.go
  server/cluster/cluster.go
  server/project/project.go
  server/repocreds/repocreds.go
  server/repository/repository.go
  util/argo/argo.go
  util/argo/argo_test.go
Labels: enhancement

#7233 feat: add test to redis_hook.go
  util/cache/redis_hook_test.go
Labels: component:test

#7316 feat: tracking method for annotations should be in another format
  reposerver/repository/repository.go
  test/e2e/deployment_test.go
  util/argo/resource_tracking.go
  util/argo/resource_tracking_test.go
Labels: enhancement

#7321 fix: core-install.yaml always refers to latest argocd image
  hack/update-manifests.sh
  manifests/core-install/kustomization.yaml
Labels: cherry-pick/2.1

#7327 fix: Rm browser history
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-details/application-resource-filter.tsx
  ui/src/app/applications/components/application-fullscreen-logs/application-fullscreen-logs.tsx
  ui/src/app/applications/components/application-pod-view/pod-view.tsx
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/applications/components/resource-details/resource-details.tsx
  ui/src/app/applications/components/utils.tsx
  ui/src/app/settings/components/clusters-list/clusters-list.tsx
  ui/src/app/settings/components/project-details/project-details.tsx
  ui/src/app/settings/components/projects-list/projects-list.tsx
Labels: bug, component:ui

#7328 feat: improve sync logic
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
  ui/src/app/applications/components/application-summary/application-summary.tsx
  ui/src/app/applications/components/resource-details/resource-details.tsx
  ui/src/app/shared/components/editable-panel/editable-panel.tsx
  ui/src/app/shared/services/applications-service.ts
Labels: component:ui
