Repository argoproj/argo-cd, pull requests merged in 2022-12, with the labels that each got.

#11272 docs: clarify finalizer effect and link to app-of-apps
  docs/user-guide/app_deletion.md
Labels: cherry-pick/2.5, ready-for-review

#11274 docs: Update Pull Request generator documentation to include application lifecycle
  docs/operator-manual/applicationset/Generators-Pull-Request.md
Labels: documentation, ready-for-review

#11120 docs: Update operator manual installation helm available url
  docs/operator-manual/installation.md
Labels: cherry-pick/2.5, ready-for-review

#8758 docs: improve Keycloak documentation for command line sign-in
  docs/operator-manual/user-management/keycloak.md
Labels: cherry-pick/2.5, ready-for-review

#10900 docs: Add CSI secret driver to the secret management options
  docs/operator-manual/secret-management.md
Labels: cherry-pick/2.5, ready-for-review

#11545 docs: Added ARGOCD_ENV_ prefix to FOO
  docs/user-guide/config-management-plugins.md
Labels: cherry-pick/2.5

#11266 [Hack] Add concurrency to cluster creation in resource generator.
  hack/gen-resources/generators/cluster_generator.go
  hack/gen-resources/util/gen_options_parser.go
  hack/gen-resources/util/sizedwaitgroup.go
Labels: enhancement, type:tech-dept

#11422 fix: use repository GithubAppCreds proxy if set (#7594)
  pkg/apis/application/v1alpha1/repository_types.go
  util/git/creds.go
Labels: enhancement, ready-for-review

#11502 feat: show app age in application list view (#11209)
  ui/src/app/applications/components/applications-list/applications-table.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
Labels: enhancement, component:ui

#11425 Allow proxy to be saved when creating repoCreds.
  assets/swagger.json
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/repository_types.go
  ui/src/app/settings/components/repos-list/repos-list.tsx
  ui/src/app/shared/services/repocreds-service.ts
  util/db/repository_secrets.go
  util/db/repository_secrets_test.go
Labels: enhancement, ready-for-review

#11565 docs: Add `skipCrds` and `ignoreMissingValueFiles` to application.yaml example
  docs/operator-manual/application.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11540 fix: helm v3 doesn't have these flags #11100
  util/helm/cmd.go
Labels: bug, cherry-pick/2.4, cherry-pick/2.5

#11327 fix(helm): login OCI Helm dependencies correctly (#11324)
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/oci-dependencies/Chart.yaml
Labels: bug, component:config-management, cherry-pick/2.4, cherry-pick/2.5, ready-for-review

#11508 fix: misc css fixes for mobile (#5705)
  ui/src/app/applications/components/application-deployment-history/application-deployment-history.tsx
  ui/src/app/applications/components/application-details/application-details.scss
  ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
  ui/src/app/applications/components/application-summary/application-summary.tsx
  ui/src/app/applications/components/applications-list/applications-list.scss
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/applications/components/resource-details/resource-details.tsx
  ui/src/app/shared/components/timestamp.tsx
Labels: component:ui, accessibility

#11613 fix: set baseURL for ApplicationSet in github_app client
  applicationset/services/internal/github_app/client.go
Labels: cherry-pick/2.4, cherry-pick/2.5

#11622 fix: only add baseURL in github_app client for GHE client
  applicationset/services/internal/github_app/client.go
Labels: cherry-pick/2.5

#11566 docs: add warning for user when using replace sync option
  docs/user-guide/sync-options.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11643 docs: kustomize has access to build environment
  docs/user-guide/kustomize.md
Labels: type:docs, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11654 chore: fix flaky e2e test (#11509)
  test/e2e/applicationset_test.go
Labels: cherry-pick/2.4, cherry-pick/2.5

#11670 chore: fix flaky e2e test
  test/e2e/applicationset_test.go
Labels: cherry-pick/2.4, cherry-pick/2.5

#11493 fix: appname in searchbar
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
  ui/src/app/shared/components/application-selector/application-selector.tsx
Labels: cherry-pick/2.5

#11170 fix: add pod age icon details in tooltip (#10290)
  ui/src/app/applications/components/application-pod-view/pod-view.scss
  ui/src/app/applications/components/application-pod-view/pod-view.tsx
Labels: cherry-pick/2.5

#11685 chore: fix flaky e2e test for immutable fields
  test/e2e/app_management_ns_test.go
  test/e2e/app_management_test.go
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11704 chore: Add Getyourguide to USERS.md
  USERS.md
Labels: only-needs-a-rubber-stamp

#11703 fix: rollback react to known working version (#11601)
  ui/package.json
  ui/yarn.lock
Labels: bug, breaking/high

#11726 chore: pin kubectl version to fix e2e test
  .github/workflows/ci-build.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11725 chore: upgrade helm to most recent version (v3.10.3)
  hack/installers/checksums/helm-v3.10.3-linux-amd64.tar.gz.sha256
  hack/installers/checksums/helm-v3.10.3-linux-arm64.tar.gz.sha256
  hack/installers/checksums/helm-v3.10.3-linux-ppc64le.tar.gz.sha256
  hack/installers/checksums/helm-v3.10.3-linux-s390x.tar.gz.sha256
  hack/tool-versions.sh
Labels: cherry-pick/2.5

#11724 fix: Unbreak termination of operation with apps in other namespaces
  ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
  ui/src/app/shared/services/applications-service.ts
Labels: cherry-pick/2.5

#11708 fix: support relative links in OCI tags query response
  util/helm/client.go
  util/helm/client_test.go
Labels: bug, component:core

#11618 feat: add google cloud source repo support (#7534)
  assets/swagger.json
  cmd/argocd/commands/repo.go
  cmd/argocd/commands/repocreds.go
  cmd/util/repo.go
  docs/assets/repo-add-google-cloud-source.png
  docs/assets/repo-add-overview.png
  docs/operator-manual/declarative-setup.md
  docs/user-guide/commands/argocd_admin_repo_generate-spec.md
  docs/user-guide/commands/argocd_repo_add.md
  docs/user-guide/commands/argocd_repocreds_add.md
  docs/user-guide/private-repositories.md
  pkg/apiclient/repository/repository.pb.go
  pkg/apis/application/v1alpha1/applicationset_types.go
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/repository_types.go
  server/repository/repository.go
  server/repository/repository.proto
  ui/src/app/settings/components/repos-list/repos-list.tsx
  ui/src/app/shared/services/repo-service.ts
  ui/src/app/shared/services/repocreds-service.ts
  util/db/repository.go
  util/db/repository_legacy.go
  util/db/repository_secrets.go
  util/git/client.go
  util/git/creds.go
  util/git/creds_test.go
  util/settings/settings.go
Labels: enhancement, component:git, ready-for-review

#10678 docs: Document applications in any namespace
  docs/operator-manual/app-any-namespace.md
  mkdocs.yml
Labels: cherry-pick/2.5

#11151 fix: sign container images by digest
  .github/workflows/image.yaml
  .github/workflows/release.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11762 doc: correct kustomize demo path
  docs/user-guide/kustomize.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11693 docs: clarify that all labels must exist
  docs/operator-manual/applicationset/Generators-Pull-Request.md
Labels: type:docs, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11753 fix: ssa e2e tests failing after updating to kubectl 1.26
  .github/workflows/ci-build.yaml
  test/e2e/app_management_ns_test.go
  test/e2e/app_management_test.go
  test/e2e/testdata/data.go
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11721 Update example dockerfile
  docs/operator-manual/custom_tools.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11720 DOCS correct URL
  docs/operator-manual/argocd-cm.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11771 docs: Bump elasticsearch version to 8.5.1 in multi-sources example
  docs/user-guide/multiple_sources.md
Labels: cherry-pick/2.6

#11773 chore: change logging level to Debug for multiple-sources manifest generation
  reposerver/repository/repository.go
Labels: cherry-pick/2.6

#11776 fix: support for enabling progressive rollouts from `argocd-cmd-params-cm`
  cmd/argocd-applicationset-controller/commands/applicationset_controller.go
  docs/operator-manual/applicationset/Progressive-Rollouts.md
  manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.6

#11775 fix: sources.ref allow hyphen and underscore (#11768)
  util/argo/argo.go
  util/argo/argo_test.go
Labels: cherry-pick/2.6

#11706 docs: clarify project destination possibilities
  docs/operator-manual/project.yaml
Labels: type:docs, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11778 chore: get image digest in seperate step
  .github/workflows/image.yaml
  .github/workflows/release.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11788 chore: fix lint error
  .github/workflows/release.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11774 fix: set Path as empty if path is not specified for a source in multiple sources (#11756)
  ui/src/app/applications/components/application-summary/application-summary.tsx
  ui/src/app/shared/components/revision.tsx
Labels: cherry-pick/2.6

#11777 Update bullet formatting on Progressive Rollouts.md
  docs/operator-manual/applicationset/Progressive-Rollouts.md
Labels: cherry-pick/2.6

#11785 fix: disable rollback button for apps with multiple sources
  ui/src/app/applications/components/application-details/application-details.tsx
Labels: multi-source-apps, cherry-pick/2.6

#11400 fix: web terminal outside argocd namespace (#11166)
  pkg/apis/application/v1alpha1/applicationset_types.go
  pkg/apis/application/v1alpha1/types.go
  server/application/application.go
  server/application/terminal.go
  server/application/terminal_test.go
  server/applicationset/applicationset.go
  server/server.go
  ui/src/app/applications/components/pod-terminal-viewer/pod-terminal-viewer.tsx
  ui/src/app/applications/components/resource-details/resource-details.tsx
  util/appset/appset.go
  util/rbac/rbac.go
  util/security/application_namespaces.go
  util/security/application_namespaces_test.go
  util/security/rbac.go
  util/security/rbac_test.go
Labels: cherry-pick/2.5, cherry-pick/2.6
