Repository argoproj/argo-cd, pull requests merged in 2022-04, with the labels that each got.

#8389 fix: credential cleanup func being called too early for plugins
  reposerver/repository/repository.go
  test/e2e/custom_tool_test.go
Labels: cherry-pick/2.3

#8969 feat!: remove rbac when using argocd cluster rm (#8958)
  cmd/argocd/commands/cluster.go
  cmd/argocd/commands/cluster_test.go
  cmd/argocd/commands/testdata/config
  test/e2e/cluster_test.go
  test/e2e/fixture/app/consequences.go
  test/e2e/fixture/cluster/actions.go
Labels: breaking/low

#8987 fix: allow cli/ui to follow logs
  pkg/apis/application/v1alpha1/cluster_constants.go
Labels: cherry-pick/2.3

#9087 fix!: added security contexts in manifests to secure argocd component
  manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml
  manifests/base/dex/argocd-dex-server-deployment.yaml
  manifests/base/notification/argocd-notifications-controller-deployment.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: breaking/low

#9096 docs: be emphatic about admin-level Projects
  docs/operator-manual/cluster-bootstrapping.md
  docs/operator-manual/declarative-setup.md
Labels: cherry-pick/2.3

#9134 chore: don't give applicationset write access to projects
  manifests/base/applicationset-controller/argocd-applicationset-controller-role.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.3

#8890 chore: Support build on s390x and ppc64le (follow #6441)
  .github/workflows/image.yaml
  hack/install.sh
  hack/installers/checksums/helm-v2.17.0-linux-ppc64le.tar.gz.sha256
  hack/installers/checksums/helm-v2.17.0-linux-s390x.tar.gz.sha256
  hack/installers/checksums/helm-v3.8.0-linux-ppc64le.tar.gz.sha256
  hack/installers/checksums/helm-v3.8.0-linux-s390x.tar.gz.sha256
  hack/installers/checksums/helm-v3.8.1-linux-ppc64le.tar.gz.sha256
  hack/installers/checksums/helm-v3.8.1-linux-s390x.tar.gz.sha256
  hack/installers/checksums/kubectl_ppc64le_1.17.8.sha256
  hack/installers/checksums/kubectl_s390x_1.17.8.sha256
  hack/installers/checksums/kustomize_4.4.1_linux_ppc64le.tar.gz.sha256
  hack/installers/checksums/kustomize_4.4.1_linux_s390x.tar.gz.sha256
  hack/installers/checksums/protoc_3.17.3_linux_ppc64le.zip.sha256
  hack/installers/checksums/protoc_3.17.3_linux_s390x.zip.sha256
  hack/installers/install-codegen-tools.sh
  hack/installers/install-kustomize.sh
  hack/installers/install-protoc.sh
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  test/container/Dockerfile
Labels: test-arm-image

#4195 fix(ui): Unscrollable error message when saving YAML (#4152)
  ui/src/app/shared/components/yaml-editor/yaml-editor.scss
  ui/src/app/shared/components/yaml-editor/yaml-editor.tsx
Labels: only-needs-a-rubber-stamp
