Repository argoproj/argo-cd, pull requests merged in 2022-01, with the labels that each got.

#8108 chore: build images on PR and conditionally build arm64 image on push
  .github/workflows/ci-build.yaml
  .github/workflows/image.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  hack/installers/checksums/awscli-linux-arm64-v2.4.6.zip.sha256
Labels: test-arm-image

#7961 feat: Allow escaping dollar in Envsubst
  docs/user-guide/build-environment.md
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
Labels: breaking/low

#8157 chore: Update to Redis 6.2.4
  .github/workflows/ci-build.yaml
  Procfile
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/container/Dockerfile
Labels: cherry-pick/2.2

#8165 fix: Fix a possible crash when parsing RBAC
  util/rbac/rbac.go
Labels: fuzzing

#8170 fix: route health check stuck in 'Progressing'
  resource_customizations/route.openshift.io/Route/health.lua
Labels: cherry-pick/2.2

#8185 fix: Prevent possible nil-pointer deref in normalizer
  util/argo/normalizers/diff_normalizer.go
  util/argo/normalizers/diff_normalizer_test.go
Labels: fuzzing

#8186 fix: Prevent possible OOB access when loading RBAC policies
  util/rbac/rbac.go
  util/rbac/rbac_test.go
Labels: fuzzing

#8226 chore: upgrade helm to most recent version (v3.7.2)
  hack/installers/checksums/helm-v3.7.2-linux-amd64.tar.gz.sha256
  hack/installers/checksums/helm-v3.7.2-linux-arm64.tar.gz.sha256
  hack/tool-versions.sh
Labels: test-arm-image

#8227 chore: upgrade kustomize to most recent version (v4.4.1)
  docs/operator-manual/upgrading/2.2-2.3.md
  hack/installers/checksums/kustomize_4.4.1_linux_amd64.tar.gz.sha256
  hack/installers/checksums/kustomize_4.4.1_linux_arm64.tar.gz.sha256
  hack/tool-versions.sh
  mkdocs.yml
Labels: test-arm-image

#8230 chore: upgrade base image to ubuntu:21.10
  Dockerfile
  test/container/Dockerfile
  test/remote/Dockerfile
Labels: test-arm-image
