Repository argoproj/argo-cd, pull requests merged in 2022-07, with the labels that each got.

#9839 fix: missing path segments for git file generator
  applicationset/generators/git.go
  applicationset/generators/git_test.go
  docs/operator-manual/applicationset/Generators-Git.md
Labels: cherry-pick/2.4

#9841 docs: Document the possibility of rendering Helm charts with Kustomize
  docs/user-guide/kustomize.md
Labels: cherry-pick/2.4

#9880 docs: getting started notes on self-signed cert (#9429)
  docs/getting_started.md
Labels: cherry-pick/2.4

#9820 fix: Make change of tracking method work at runtime
  controller/cache/cache.go
  test/e2e/app_management_test.go
  test/e2e/fixture/app/actions.go
  test/e2e/fixture/app/context.go
  test/e2e/fixture/fixture.go
  util/argo/resource_tracking.go
  util/settings/settings.go
Labels: cherry-pick/2.4

#9895 fix: 'unexpected reserved bits' breaking web terminal (#9605)
  docs/operator-manual/argocd-cm.yaml
  server/application/terminal.go
  server/application/websocket.go
  server/server.go
  util/settings/settings.go
Labels: cherry-pick/2.4

#9911 fix: NotAfter is not set when ValidFor is set
  util/tls/tls.go
  util/tls/tls_test.go
Labels: cherry-pick/2.4

#9922 fix: CMP manifest generation fails with ENHANCE_YOUR_CALM if over 40s
  cmpserver/server.go
  common/common.go
  reposerver/server.go
  server/server.go
  util/grpc/grpc.go
Labels: cherry-pick/2.4

#9921 test: Use dedicated multi-arch workloads in e2e tests
  test/e2e/app_management_test.go
  test/e2e/diff_test.go
  test/e2e/fixture/project/context.go
  test/e2e/hook_test.go
  test/e2e/multiarch-container/Dockerfile
  test/e2e/multiarch-container/build.sh
  test/e2e/testdata/cluster-role/pod.yaml
  test/e2e/testdata/crd-validation/deployment.yaml
  test/e2e/testdata/deployment/deployment.yaml
  test/e2e/testdata/deprecated-extensions/deployment.yaml
  test/e2e/testdata/git-submodule/submodule-pod.yaml
  test/e2e/testdata/guestbook-logs/guestbook-ui-deployment.yaml
  test/e2e/testdata/guestbook-with-namespace/guestbook-ui-deployment-ns.yaml
  test/e2e/testdata/guestbook-with-namespace/guestbook-ui-deployment.yaml
  test/e2e/testdata/guestbook/guestbook-ui-deployment.yaml
  test/e2e/testdata/guestbook_local/guestbook-ui-deployment.yaml
  test/e2e/testdata/hook-and-deployment/deployment.yaml
  test/e2e/testdata/hook-and-deployment/hook.yaml
  test/e2e/testdata/hook/hook.yaml
  test/e2e/testdata/hook/pod.yaml
  test/e2e/testdata/kustomize/pod.yaml
  test/e2e/testdata/multi-namespace-hook/multi-namespace-hook.yaml
  test/e2e/testdata/multi-namespace/deployment-with-namespace.yaml
  test/e2e/testdata/multi-namespace/deployment.yaml
  test/e2e/testdata/networking/guestbook-ui-deployment.yaml
  test/e2e/testdata/one-deployment/deployment.yaml
  test/e2e/testdata/two-nice-pods/pod-1.yaml
  test/e2e/testdata/two-nice-pods/pod-2.yaml
Labels: cherry-pick/2.4

#9949 Update Generators-Git.md
  docs/operator-manual/applicationset/Generators-Git.md
Labels: cherry-pick/2.4

#9926 docs: fix Ingress documentation for AWS ALBs
  docs/operator-manual/ingress.md
Labels: cherry-pick/2.4

#9983 fix: add missing download CLI tool URL response for ppc64le, s390x
  util/settings/settings.go
  util/settings/settings_test.go
Labels: cherry-pick/2.4

#9989 fix: e2e test to use func from clusterauth instead creating one with old logic
  test/e2e/fixture/applicationsets/actions.go
Labels: cherry-pick/2.4

#10011 fix: terminal websocket write lock to avoid races
  server/application/websocket.go
Labels: cherry-pick/2.4

#9997 docs: document directory app include/exclude fields
  docs/operator-manual/application.yaml
Labels: cherry-pick/2.4

#9995 docs: use quotes to emphasize that ConfigMap value is a string
  docs/operator-manual/web_based_terminal.md
Labels: cherry-pick/2.4

#10042 chore: upgrade Dex to 2.32.0 (#10036)
  manifests/base/dex/argocd-dex-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4

#10031 chore: update redis to avoid CVE-2022-2097
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: cherry-pick/2.4

#10059 chore: update redis to 7.0.4 to avoid CVE-2022-30065
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/container/Dockerfile
Labels: cherry-pick/2.4

#10078 typo: user->use
  docs/operator-manual/user-management/google.md
Labels: cherry-pick/2.4

#10018 fix: Set HOST_ARCH for yarn build from platform
  Dockerfile
  docs/operator-manual/argocd-cm.yaml
  ui/src/app/help/components/help.tsx
Labels: test-arm-image

#10087 docs: add api field example in the appset security doc
  docs/operator-manual/applicationset/Security.md
Labels: cherry-pick/2.4

#10116 fix: skip redirect url validation when it's the base href (#10058)
  util/oidc/oidc.go
  util/oidc/oidc_test.go
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4
