Repository argoproj/argo-cd, pull requests merged in 2022-10, with the labels that each got.

#10702 chore: Upgrade shipped version of Redis to 7.0.5 to fix CVE-2022-35951
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/container/Dockerfile
Labels: cherry-pick/2.4

#10591 docs: syncWindows in project.yaml
  docs/operator-manual/project.yaml
Labels: cherry-pick/2.4

#10744 docs: fix broken links in faq.md
  docs/faq.md
Labels: cherry-pick/2.4

#10775 chore: upgrade Dex to 2.35.0
  .github/workflows/ci-build.yaml
  manifests/base/dex/argocd-dex-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4

#10799 chore: upgrade dex to v2.35.1 (#10797)
  .github/workflows/ci-build.yaml
  manifests/base/dex/argocd-dex-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4

#10764 docs: add declarative syntax examples for helm
  docs/user-guide/helm.md
Labels: cherry-pick/2.4

#10813 docs: `#argo-contributors` instead of `#argo-dev` in FAQ
  docs/developer-guide/faq.md
Labels: cherry-pick/2.4

#10822 docs: update Server-Side Apply docs for patching of existing resources (#10821)
  docs/user-guide/sync-options.md
Labels: cherry-pick/2.5

#10829 docs: Add example about how to patch with SSA syncs
  docs/user-guide/sync-options.md
Labels: cherry-pick/2.5

#10826 fix(ui): Don't jump back to tiles view on app deletion
  ui/src/app/applications/components/application-details/application-details.tsx
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10833 fix: add applicationset to crds generated by gen-crd-spec
  hack/gen-crd-spec/main.go
  manifests/core-install.yaml
  manifests/crds/applicationset-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
Labels: cherry-pick/2.4, cherry-pick/2.5

#10825 fix: Unbreak app refresh from panel list
  ui/src/app/applications/components/applications-list/applications-list.tsx
Labels: cherry-pick/2.5

#10776 docs: Correct grammar issues in docs on manifest path annotations
  docs/operator-manual/high_availability.md
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10619 docs: fix advice about preferred version in high availability
  docs/operator-manual/high_availability.md
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10513 fix: applicationset controller should respect logging flags (#10399)
  applicationset/controllers/applicationset_controller.go
  applicationset/controllers/applicationset_controller_test.go
  cmd/argocd-applicationset-controller/commands/applicationset_controller.go
Labels: cherry-pick/2.5

#10304 docs: remove unused plugin config fields
  cmpserver/plugin/config.go
  cmpserver/plugin/testdata/ksonnet/config/plugin.yaml
  cmpserver/plugin/testdata/kustomize-neg/config/plugin-bad.yaml
  cmpserver/plugin/testdata/kustomize/config/plugin.yaml
  docs/proposals/config-management-plugin-v2.md
  manifests/core-install.yaml
  manifests/crds/application-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
  test/cmp/plugin.yaml
  test/e2e/testdata/cmp-find-command/plugin.yaml
  test/e2e/testdata/cmp-find-glob/plugin.yaml
Labels: cherry-pick/2.4

#10342 docs: more versioned docs fixes
  docs/developer-guide/api-docs.md
  docs/faq.md
  docs/user-guide/private-repositories.md
  docs/user-guide/sync-options.md
Labels: cherry-pick/2.5

#10867 fix: added css to change cursor to pointer on hover (#10864)
  ui/src/app/applications/components/utils.scss
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10862 fix: clicking `HEAD` in bitbucket leads to a 404 page
  ui/src/app/shared/components/urls.ts
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10876 fix(ui): sync option label doesn't check corresponding box
  ui/src/app/applications/components/application-retry-options/application-retry-options.tsx
  ui/src/app/applications/components/application-sync-options/application-sync-options.tsx
  ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx
  ui/src/app/applications/components/applications-sync-panel/applications-sync-panel.tsx
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10891 fix: add full permission for admins to applicationsets in RBAC policy (#10810)
  assets/builtin-policy.csv
Labels: hacktoberfest, cherry-pick/2.5

#10879 docs: more docs for directory apps
  docs/operator-manual/application.yaml
  docs/user-guide/directory.md
  mkdocs.yml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10808 docs: add link to 2.4-2.5 upgrade guide
  docs/operator-manual/upgrading/overview.md
Labels: cherry-pick/2.4, cherry-pick/2.5

#10906 chore: improve log in argo-cd/applicationset/generators/generator_spec_processor.go
  applicationset/generators/generator_spec_processor.go
Labels: hacktoberfest

#10932 fix: Resource list loading slowly due to Sync Wave sorting
  assets/swagger.json
  controller/state.go
  manifests/core-install.yaml
  manifests/crds/application-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-details/application-resource-list.tsx
  ui/src/app/shared/models.ts
Labels: cherry-pick/2.5

#10934 feat: Adding bcrypt support for argocd CLI
  cmd/argocd/commands/account.go
  cmd/argocd/commands/bcrypt.go
  cmd/argocd/commands/bcrypt_test.go
  docs/faq.md
  docs/user-guide/commands/argocd_account.md
  docs/user-guide/commands/argocd_account_bcrypt.md
Labels: hacktoberfest

#10940 chore: wrap error objects to include context (#10592) #10905
  applicationset/services/scm_provider/gitea.go
  hack/gen-resources/generators/project_generator.go
  reposerver/repository/lock.go
  util/notification/settings/legacy.go
  util/settings/accounts.go
Labels: hacktoberfest

#10967 chore: release signature documentation
  argocd-cosign.pub
  docs/operator-manual/signed-release-assets.md
  hack/generate-release-notes.sh
  mkdocs.yml
Labels: cherry-pick/2.4, cherry-pick/2.5

#10939 chore: upgrade dex to v2.35.3 to avoid CVE-2022-27665
  .github/workflows/ci-build.yaml
  manifests/base/dex/argocd-dex-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10969 chore: release signature of sbom
  .github/workflows/release.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10937 fix: upgrade Helm to avoid disk use issue (#8773)
  docs/operator-manual/upgrading/2.4-2.5.md
  hack/installers/checksums/helm-v3.10.1-linux-amd64.tar.gz.sha256
  hack/installers/checksums/helm-v3.10.1-linux-arm64.tar.gz.sha256
  hack/installers/checksums/helm-v3.10.1-linux-ppc64le.tar.gz.sha256
  hack/installers/checksums/helm-v3.10.1-linux-s390x.tar.gz.sha256
  hack/tool-versions.sh
Labels: cherry-pick/2.5

#10954 feat: directory app include/exclude fields in UI (#10880)
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
  ui/src/app/shared/models.ts
Labels: hacktoberfest

#10958 feat: UI Add copy to clipboard shortcut
  ui/src/app/applications/components/application-node-info/application-node-info.tsx
  ui/src/app/shared/components/clipboard-text.tsx
  ui/src/app/shared/components/index.ts
Labels: hacktoberfest

#10944 chore: improve error logs
  applicationset/utils/createOrUpdate.go
  cmd/argocd/commands/admin/app.go
  cmd/argocd/commands/admin/generatespec_utils.go
  cmd/argocd/commands/admin/project.go
  cmd/util/applicationset.go
  controller/clusterinfoupdater.go
Labels: hacktoberfest

#10956 chore: Enhance title & description for Certificates on settings page
  ui/src/app/settings/components/certs-list/certs-list.tsx
  ui/src/app/settings/components/settings-overview/settings-overview.tsx
Labels: hacktoberfest

#10970 fix: Resource list in sync page msg style#10887
  ui/src/app/applications/components/application-details/application-details.scss
  ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#10960 chore: updated error message to include context
  reposerver/server.go
Labels: hacktoberfest

#10980 controller/hearth: decreased indent level in setApplicationHealth
  controller/health.go
Labels: hacktoberfest

#10995 fix: Update custom health check for kiali.io/Kiali
  resource_customizations/kiali.io/Kiali/health.lua
  resource_customizations/kiali.io/Kiali/health_test.yaml
  resource_customizations/kiali.io/Kiali/testdata/degraded.yaml
  resource_customizations/kiali.io/Kiali/testdata/healthy.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11005 chore: fix e2e
  test/e2e/fixture/fixture.go
  util/git/client_test.go
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11026 docs: mention that OCI helm does not support version ranges
  docs/user-guide/tracking_strategies.md
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4

#11038 docs: fix 'bellow' typos
  docs/operator-manual/metrics.md
  docs/proposals/proxy-extensions.md
  docs/user-guide/diffing.md
  docs/user-guide/sync-options.md
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11042 chore: migrate import statements from es5 to es6
  ui/src/app/applications/components/application-conditions/application-conditions.tsx
  ui/src/app/applications/components/application-create-panel/application-create-panel.tsx
  ui/src/app/applications/components/application-deployment-history/application-deployment-history.tsx
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-node-info/application-node-info.tsx
  ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
  ui/src/app/applications/components/application-resources-diff/application-resources-diff.tsx
  ui/src/app/applications/components/application-resources-diff/individual-diff-section.tsx
  ui/src/app/applications/components/application-retry-options/application-retry-options.tsx
  ui/src/app/applications/components/application-retry-view/application-retry-view.tsx
  ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
  ui/src/app/applications/components/application-summary/application-summary.tsx
  ui/src/app/applications/components/application-summary/edit-notification-subscriptions.tsx
  ui/src/app/applications/components/application-sync-options/application-sync-options.tsx
  ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx
  ui/src/app/applications/components/applications-list/applications-labels.tsx
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/applications/components/applications-list/applications-source.tsx
  ui/src/app/applications/components/applications-list/applications-status-bar.tsx
  ui/src/app/applications/components/applications-list/applications-table.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
  ui/src/app/user-info/components/user-info-overview/user-info-overview.tsx
Labels: hacktoberfest, hacktoberfest-accepted
