Repository argoproj/argo-cd, pull requests merged in 2022-05, with the labels that each got.

#9345 docs: logs RBAC upgrate notes
  docs/operator-manual/upgrading/2.3-2.4.md
Labels: cherry-pick/2.4

#9301 feat(manifests): Add service account for repo server
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/base/repo-server/argocd-repo-server-sa.yaml
  manifests/base/repo-server/kustomization.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  reposerver/repository/repository_test.go
Labels: cherry-pick/2.4

#9354 docs: clarify Role/ClusterRole uses for exec feature
  docs/operator-manual/rbac.md
Labels: cherry-pick/2.4

#9347 chore: ignore irrelevant go-restful vulnerability
  .snyk
Labels: cherry-pick/2.3, cherry-pick/2.4

#9389 docs: plugins need their own writeable tmp volume
  docs/operator-manual/upgrading/2.3-2.4.md
  docs/user-guide/config-management-plugins.md
Labels: cherry-pick/2.4

#9371 chore: Improve otel grpc traces adding span correlation
  Procfile
  cmd/argocd-application-controller/commands/argocd_application_controller.go
  cmpserver/apiclient/clientset.go
  docs/operator-manual/argocd-cmd-params-cm.yaml
  docs/operator-manual/server-commands/argocd-application-controller.md
  manifests/base/application-controller/argocd-application-controller-statefulset.yaml
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/base/server/argocd-server-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  reposerver/apiclient/clientset.go
  server/server.go
Labels: cherry-pick/2.4

#9416 fix: update filter combo-box icon color
  ui/src/app/applications/components/applications-list/applications-filter.tsx
Labels: cherry-pick/2.4

#9385 feat: support pod exec terminal logging
  applicationset/generators/cluster.go
  server/application/application.go
  server/application/terminal.go
  server/application/terminal_test.go
Labels: cherry-pick/2.4

#9466 docs: more appset security docs
  docs/operator-manual/applicationset/Generators-Cluster.md
  docs/operator-manual/applicationset/Generators-Git.md
  docs/operator-manual/applicationset/Generators-List.md
  docs/operator-manual/applicationset/Generators-Pull-Request.md
  docs/operator-manual/applicationset/Generators-SCM-Provider.md
  docs/operator-manual/applicationset/Getting-Started.md
  docs/operator-manual/applicationset/Security.md
  docs/operator-manual/applicationset/index.md
  docs/operator-manual/security.md
  docs/user-guide/application-set.md
  mkdocs.yml
Labels: cherry-pick/2.4

#9387 docs: fix PR generators list
  docs/operator-manual/applicationset/Generators-Pull-Request.md
Labels: cherry-pick/2.4

#9434 fix: avoid k8s call before authorization for terminal endpoint
  assets/builtin-policy.csv
  docs/operator-manual/rbac.md
  docs/operator-manual/upgrading/2.3-2.4.md
  server/application/terminal.go
  server/application/terminal_test.go
  ui/src/app/applications/components/pod-terminal-viewer/pod-terminal-viewer.tsx
  ui/src/app/applications/components/resource-details/resource-details.tsx
Labels: cherry-pick/2.4

#9520 enhance: radio button click experience problem (#9518)
  ui/src/app/applications/components/utils.tsx
Labels: accessibility

#9170 fix: Ignore diff with schema
  cmd/argocd/commands/admin/app_test.go
  controller/appcontroller.go
  controller/appcontroller_test.go
  controller/state.go
  controller/sync.go
  go.mod
  go.sum
  util/argo/diff/diff.go
  util/argo/managedfields/managed_fields.go
  util/argo/managedfields/managed_fields_test.go
  util/argo/managedfields/parser.go
  util/argo/testdata/data.go
  util/argo/testdata/desired_validating_webhook.yaml
  util/argo/testdata/live_validating_webhook.yaml
Labels: cherry-pick/2.4
