Repository argoproj/argo-cd, pull requests merged in 2022-11, with the labels that each got.

#11141 chore: don't generate release notes
  .github/workflows/release.yaml
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4

#11176 fix: upgrade redis-ha chart to 4.22.3, redis regression
  manifests/base/redis/argocd-redis-network-policy.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/argocd-redis-ha-proxy-network-policy.yaml
  manifests/ha/base/redis-ha/argocd-redis-ha-server-network-policy.yaml
  manifests/ha/base/redis-ha/chart/requirements.lock
  manifests/ha/base/redis-ha/chart/requirements.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/base/redis-ha/overlays/statefulset-containers-securityContext.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.5

#11012 fix: handle apiGroup updates in resource-tracking
  controller/state.go
  controller/state_test.go
  controller/sync.go
  util/argo/diff/diff.go
  util/argo/resource_tracking.go
Labels: cherry-pick/2.4, cherry-pick/2.5

#11163 fix: templating keys in ApplicationSet (#11076)
  applicationset/utils/utils.go
  applicationset/utils/utils_test.go
Labels: cherry-pick/2.5

#11185 chore: add debug logs around CMP manifest generation
  cmpserver/plugin/plugin.go
  docs/user-guide/config-management-plugins.md
  reposerver/repository/repository.go
Labels: cherry-pick/2.5

#11130 docs: add Dockerfile example for plugin
  docs/user-guide/config-management-plugins.md
Labels: cherry-pick/2.5

#10929 docs: document metadata access for go-templated cluster generator
  docs/operator-manual/applicationset/GoTemplate.md
Labels: cherry-pick/2.5

#11108 docs: Add Contributor's Quickstart Page
  docs/developer-guide/contributors-quickstart.md
  mkdocs.yml
Labels: cherry-pick/2.5

#11127 docs: add Pigment to list of users
  USERS.md
Labels: cherry-pick/2.5

#11219 fix: use non distroless image for dex
  .github/workflows/ci-build.yaml
  manifests/base/dex/argocd-dex-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11187 docs: add example for config management plugins exclusion
  docs/user-guide/config-management-plugins.md
Labels: cherry-pick/2.5

#11218 fix(ui): show orphaned as gray. fixes: #11180
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.scss
Labels: cherry-pick/2.5

#11245 docs: fix formatting
  docs/user-guide/config-management-plugins.md
Labels: cherry-pick/2.5

#10988 fix: add check for trailing/leading whitespace in project role group names (#10919)
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
Labels: hacktoberfest

#11119 fix: allow resolving repo root as jsonnt lib path
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/jsonnet-1/guestbook-ui.jsonnet
  reposerver/repository/testdata/jsonnet-1/params.libsonnet
  reposerver/repository/testdata/jsonnet-1/vendor/nested/service.libsonnet
  util/helm/helm.go
  util/helm/helm_test.go
  util/io/path/resolved.go
  util/io/path/resolved_test.go
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11291 docs: Use new Google Analytics 4 ID
  mkdocs.yml
Labels: only-needs-a-rubber-stamp, ready-for-review

#11331 chore: use --password-stdin for docker login
  .github/workflows/image.yaml
  .github/workflows/release.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#9813 fix: UI can now get clusters with slashes in name (#9812)
  server/cluster/cluster.go
  server/cluster/cluster_test.go
  ui/src/app/shared/services/clusters-service.ts
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11285 fix: set HELM_CONFIG_HOME dir for oci registry authentication; fixes: #11284
  util/helm/cmd.go
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review

#11200 feat: display auto sync status in application details view
  ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
Labels: component:ui

#11316 fix(ui): fix sorting of parameters. Make the Remove override button clickable again
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
Labels: component:ui, ready-for-review

#11153 feature: allow a custom labels on any resource to surface in the UI (tree view node tags)
  controller/cache/cache.go
  controller/cache/info.go
  controller/cache/info_test.go
  docs/operator-manual/argocd-cm.yaml
  docs/operator-manual/declarative-setup.md
  util/settings/settings.go
Labels: enhancement, component:ui

#11342 chore: add Wolffun Game to USERS.md
  USERS.md
Labels: only-needs-a-rubber-stamp, ready-for-review

#11336 docs: add user to list
  USERS.md
Labels: only-needs-a-rubber-stamp, ready-for-review

#11323 docs: Enable Google Analytics 4 for 2.5 (stable)
  Makefile
  docs/requirements.txt
  mkdocs.yml
Labels: ready-for-review

#11322 fix: remove 0.0.0.0/0 ipblock from network policies (#11321)
  USERS.md
  manifests/base/redis/argocd-redis-network-policy.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/argocd-redis-ha-proxy-network-policy.yaml
  manifests/ha/base/redis-ha/argocd-redis-ha-server-network-policy.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.5, ready-for-review

#11246 fix: application stuck in infinite reconciliation loop if using wrong project
  controller/appcontroller.go
  controller/appcontroller_test.go
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11192 feat: Implement karmada CRD health checks
  resource_customizations/work.karmada.io/ClusterResourceBinding/health.lua
  resource_customizations/work.karmada.io/ClusterResourceBinding/health_test.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/degraded_unapplied.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/degraded_unhealth.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/degraded_unknown.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/health.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/health_unknown.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/progressing.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/progressing_aggregatedStatus.yaml
  resource_customizations/work.karmada.io/ClusterResourceBinding/testdata/progressing_cluster.yaml
  resource_customizations/work.karmada.io/ResourceBinding/health.lua
  resource_customizations/work.karmada.io/ResourceBinding/health_test.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/degraded_unapplied.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/degraded_unhealth.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/degraded_unknown.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/health.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/health_unknown.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/progressing.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/progressing_aggregatedStatus.yaml
  resource_customizations/work.karmada.io/ResourceBinding/testdata/progressing_cluster.yaml
Labels: ready-for-review

#11181 docs: fix references to cli tools moved under argocd admin
  cmd/argocd/commands/admin/notifications.go
  docs/operator-manual/notifications/troubleshooting-commands.md
  docs/operator-manual/notifications/troubleshooting.md
  docs/user-guide/commands/argocd_admin_notifications_template_get.md
  docs/user-guide/commands/argocd_admin_notifications_template_notify.md
  docs/user-guide/commands/argocd_admin_notifications_trigger_get.md
  docs/user-guide/commands/argocd_admin_notifications_trigger_run.md
  hack/gen-catalog/main.go
  mkdocs.yml
Labels: documentation, cherry-pick/2.5, ready-for-review

#11384 bug(ui): fix incomplete drop-down resource actions
  ui/src/app/applications/components/utils.tsx
Labels: bug, bug/priority:high

#11247 fix: hide app namespace on the ui
  assets/swagger.json
  pkg/apiclient/settings/settings.pb.go
  server/server.go
  server/settings/settings.go
  server/settings/settings.proto
  ui/src/app/app.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
  ui/src/app/applications/components/utils.tsx
  ui/src/app/shared/components/application-selector/application-selector.tsx
  ui/src/app/shared/context.ts
  ui/src/app/shared/models.ts
  util/settings/settings.go
Labels: component:ui, cherry-pick/2.5

#11424 chore: update remote-debugging-docs
  docs/developer-guide/debugging-remote-environment.md
Labels: documentation, only-needs-a-rubber-stamp, ready-for-review

#11409 fix: Adds support for /api/v1/applicationsets* via HTTP.
  server/server.go
Labels: cherry-pick/2.5

#11429 docs: improve build env variable list formatting
  docs/user-guide/build-environment.md
Labels: cherry-pick/2.5

#10641 feat: Add wildcard support in OCI Helm Repositories targetRevision (#6686)
  reposerver/repository/repository.go
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
  util/helm/client.go
  util/helm/client_test.go
  util/helm/mocks/Client.go
  util/helm/tags.go
  util/helm/tags_test.go
Labels: component:config-management

#11101 fix: ui banner covering sidebar
  ui/src/app/ui-banner/ui-banner.scss
  ui/src/app/ui-banner/ui-banner.tsx
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, ready-for-review

#11460 docs: Fix markdown formatting
  docs/operator-manual/metrics.md
Labels: cherry-pick/2.5

#10999 chore: use set-output environment file
  .github/workflows/image.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11447 fix: upgrade golang.org/x/net to avoid CVE-2022-27664
  go.mod
  go.sum
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5
