Repository argoproj/argo-cd, pull requests merged in 2022-06, with the labels that each got.

#9564 ci: remove cache from image build
  .github/workflows/image.yaml
Labels: test-arm-image

#9548 docs: document plugin prefixed env vars
  docs/operator-manual/upgrading/2.3-2.4.md
  docs/user-guide/config-management-plugins.md
Labels: cherry-pick/2.4

#8413 Document `action` RBAC action and application resource path. Relates to #3279
  docs/operator-manual/rbac.md
Labels: cherry-pick/2.4

#9566 fix: missing Helm params (#9565)
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/values-files/Chart.yaml
  reposerver/repository/testdata/values-files/caps-extn-values.YAML
  reposerver/repository/testdata/values-files/exclude.yaml
  reposerver/repository/testdata/values-files/has-the-word-values.yaml
  reposerver/repository/testdata/values-files/values.yaml
  reposerver/repository/testdata/values-files/values.yml
  server/server_test.go
  util/helm/helm.go
  util/helm/helm_test.go
  util/io/path/resolved.go
Labels: cherry-pick/2.4

#9561 chore: update Kex-Algorithms
  go.mod
  go.sum
  util/git/ssh.go
Labels: cherry-pick/2.4

#9563 chore: upgrade base image for test containers Ubuntu:22.04
  test/container/Dockerfile
  test/remote/Dockerfile
Labels: cherry-pick/2.4

#9551 chore: upgrade base image to ubuntu:22.04
  Dockerfile
Labels: cherry-pick/2.4

#9546 fix: create serviceaccount token for v1.24 clusters
  cmd/argocd/commands/admin/cluster.go
  cmd/argocd/commands/cluster.go
  common/common.go
  go.mod
  test/e2e/cluster_test.go
  test/e2e/fixture/cluster/actions.go
  util/clusterauth/clusterauth.go
  util/clusterauth/clusterauth_test.go
Labels: cherry-pick/2.4

#9611 docs: document argocd cluster add behavior for 1.24 clusters
  docs/operator-manual/security.md
Labels: cherry-pick/2.4

#9614 fix: use serviceaccount name instead of struct
  util/clusterauth/clusterauth.go
Labels: cherry-pick/2.4

#9615 docs: document OpenSSH upgrade (#9598)
  docs/operator-manual/upgrading/2.3-2.4.md
  docs/user-guide/private-repositories.md
Labels: cherry-pick/2.4

#9587 chore: use Ubuntu 22.04 in CI
  .github/workflows/ci-build.yaml
  .github/workflows/codeql.yml
  .github/workflows/image.yaml
  .github/workflows/release.yaml
Labels: cherry-pick/2.4

#9632 docs: update Generators-Git.md
  docs/operator-manual/applicationset/Generators-Git.md
Labels: cherry-pick/2.4

#9601 fix: overrides should not appear in the manifest cache key
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/app-parameters/single-global-helm/.argocd-source.yaml
  reposerver/repository/testdata/app-parameters/single-global-helm/Chart.yaml
  reposerver/repository/testdata/app-parameters/single-global-helm/templates/deployment.yaml
  reposerver/repository/testdata/app-parameters/single-global-helm/values.yaml
Labels: cherry-pick/2.4

#9709 fix: project filter (#9651)
  ui/src/app/shared/services/applications-service.ts
Labels: cherry-pick/2.4

#9724 fix: updated baseHRefRegex to perform lazy match
  server/server.go
  server/server_test.go
Labels: cherry-pick/2.4

#9732 fix: updated config file permission requirements for windows (#9666)
  util/localconfig/file_perm_unix.go
  util/localconfig/file_perm_windows.go
  util/localconfig/localconfig.go
  util/localconfig/localconfig_test.go
Labels: cherry-pick/2.4

#9734 test/remote: Allow override of base image
  test/remote/Dockerfile
Labels: cherry-pick/2.4

#9671 fix: webhook incorrectly misses cache on GenerateManifests (#9670)
  util/webhook/webhook.go
Labels: cherry-pick/2.2, cherry-pick/2.3, cherry-pick/2.4

#9799 docs: explain rightmost git generator path parameter behavior
  docs/operator-manual/applicationset/Generators-Git.md
Labels: cherry-pick/2.4

#9784 docs: getting started notes on self-signed cert (#9429)
  docs/faq.md
  docs/getting_started.md
Labels: cherry-pick/2.4

#9728 fix: provide nameNormalized param for local cluster in ApplicationSet cluster generator (#9727)
  applicationset/generators/cluster.go
  applicationset/generators/cluster_test.go
Labels: cherry-pick/2.4

#9789 fix: configurable CMP tar exclusions (#9675)
  USERS.md
  cmd/argocd-repo-server/commands/argocd_repo_server.go
  docs/operator-manual/argocd-cmd-params-cm.yaml
  docs/operator-manual/server-commands/argocd-repo-server.md
  docs/user-guide/config-management-plugins.md
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  util/app/discovery/discovery.go
  util/app/discovery/discovery_test.go
  util/cmp/stream.go
  util/cmp/stream_test.go
  util/cmp/testdata/app/DUMMY.md
  util/cmp/testdata/app/dummy/DUMMY2.md
  util/env/env.go
Labels: cherry-pick/2.4

#9833 fix: support resource logs and exec #9783
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
Labels: cherry-pick/2.4

#9826 chore: upgrade parse-url to avoid SNYK-JS-PARSEURL-2936249
  ui/yarn.lock
Labels: cherry-pick/2.4

#9835 docs: custom secret must be labeled
  docs/operator-manual/user-management/index.md
Labels: cherry-pick/2.4

#9842 fix: make sure api server informer does not stop after setting change
  cmd/argocd-server/commands/argocd_server.go
  cmd/argocd/commands/headless/headless.go
  server/server.go
  server/server_norace_test.go
  server/server_test.go
Labels: cherry-pick/2.4
