Repository argoproj/argo-cd, pull requests merged in 2023-05, with the labels that each got.

#13388 chore: upgrade haproxy to 2.6.12 to avoid CVE-2023-0464
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: cherry-pick/2.5, cherry-pick/2.6

#13389 chore: upgrade redis to 7.0.11 to avoid CVE-2023-0464
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/container/Dockerfile
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12859 chore(deps): bump library/golang from 1.19.6 to 1.19.7
  Dockerfile
  test/container/Dockerfile
  test/remote/Dockerfile
Labels: ready-for-review

#12921 docs: nginx passthrough secret as argocd-server-tls
  docs/operator-manual/ingress.md
Labels: documentation, ready-for-review, size/XS

#13368 chore: Bump version to the next release version 2.8.0
  VERSION
Labels: ready-for-review

#13300 chore: Add DaoCloud into USERS
  USERS.md
Labels: ready-for-review

#13304 docs: Add Hostinger to USERS.md
  USERS.md
Labels: ready-for-review

#13303 chore: Add ScaleFactory to USERS.md
  USERS.md
Labels: ready-for-review

#13288 chore: Add Puzzle to the users list
  USERS.md
Labels: ready-for-review

#13143 feat: add MariaDB CRD health checks
  resource_customizations/mariadb.mmontes.io/MariaDB/health.lua
  resource_customizations/mariadb.mmontes.io/MariaDB/health_test.yaml
  resource_customizations/mariadb.mmontes.io/MariaDB/testdata/mariadb_error.yaml
  resource_customizations/mariadb.mmontes.io/MariaDB/testdata/no_status.yaml
  resource_customizations/mariadb.mmontes.io/MariaDB/testdata/restore_complete.yaml
  resource_customizations/mariadb.mmontes.io/MariaDB/testdata/restore_not_complete.yaml
  resource_customizations/mariadb.mmontes.io/MariaDB/testdata/statefulset_not_ready.yaml
  resource_customizations/mariadb.mmontes.io/MariaDB/testdata/statefulset_ready.yaml
Labels: ready-for-review

#13292 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  cmd/argocd-dex/commands/argocd_dex.go
  cmd/argocd/commands/account.go
  cmd/argocd/commands/admin/admin.go
  cmd/argocd/commands/admin/app.go
  cmd/argocd/commands/admin/backup.go
  cmd/argocd/commands/admin/generatespec_utils.go
  cmd/argocd/commands/admin/project_allowlist.go
  cmd/argocd/commands/admin/settings.go
  cmd/argocd/commands/admin/settings_rbac.go
  cmd/argocd/commands/app.go
  cmd/argocd/commands/app_actions.go
  cmd/argocd/commands/common.go
  cmd/argocd/commands/project.go
  cmd/util/cluster.go
  cmd/util/cluster_test.go
  controller/appcontroller_test.go
  controller/cache/info_test.go
  controller/health_test.go
  controller/metrics/metrics_test.go
  go.mod
  hack/gen-catalog/main.go
  hack/gen-crd-spec/main.go
  pkg/apis/application/v1alpha1/types.go
  reposerver/repository/chart.go
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  server/application/application_test.go
  server/extension/extension.go
  server/server_test.go
  server/settings/settings.go
  test/e2e/fixture/fixture.go
  test/testutil.go
  util/argo/managedfields/managed_fields_test.go
  util/argo/normalizers/diff_normalizer_test.go
  util/argo/normalizers/knowntypes_normalizer_test.go
  util/clusterauth/clusterauth_test.go
  util/config/reader.go
  util/dex/config.go
  util/dex/dex_test.go
  util/helm/helm.go
  util/kube/kube_test.go
  util/lua/custom_actions_test.go
  util/lua/health_test.go
  util/lua/lua_test.go
  util/notification/settings/legacy.go
  util/notification/settings/settings.go
  util/settings/settings.go
Labels: ready-for-review

#13412 docs: Add Cloudogu to USERS.md
  USERS.md
Labels: ready-for-review

#13061 fix: interpolate gen fix (#12716)
  applicationset/generators/matrix.go
  applicationset/generators/matrix_test.go
Labels: ready-for-review

#13515 docs: Add Procore as a user of Argo CD
  USERS.md
Labels: ready-for-review

#13499 docs(users): add StreamNative to the list of users
  USERS.md
Labels: ready-for-review

#13474 fix: update container log view on select
  ui/src/app/applications/components/pod-logs-viewer/container-selector.tsx
Labels: cherry-pick/2.7

#12168 docs: Remove old annotations
  docs/operator-manual/ingress.md
Labels: ready-for-review

#12949 fix(appset): handle templating of raw JSON fields (#12947)
  applicationset/generators/matrix_test.go
  applicationset/utils/utils.go
Labels: ready-for-review

#13664 fix: deeplinks API checking wrong permissions
  server/application/application.go
Labels: cherry-pick/2.7

#13637 fix: argocd app sync/wait falsely failed with completed with phase: Running
  cmd/argocd/commands/app.go
Labels: cherry-pick/2.6, cherry-pick/2.7

#13677 fix: typo in manifest
  assets/swagger.json
  manifests/core-install.yaml
  manifests/crds/application-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
Labels: ready-for-review

#13301 chore: Add Veepee into USERS
  USERS.md
Labels: ready-for-review

#12068 fix: ui dark theme transition
  ui/src/app/applications/components/application-resources-diff/application-resources-diff.scss
  ui/src/app/shared/components/layout/layout.tsx
Labels: cherry-pick/2.7

#12255 fix: surface source not permitted errors
  cmd/argocd/commands/app.go
  cmd/argocd/commands/project.go
  controller/state.go
  reposerver/apiclient/repository.pb.go
  reposerver/repository/repository.go
  reposerver/repository/repository.proto
  reposerver/repository/repository_test.go
  server/application/application.go
  test/e2e/helm_test.go
  test/e2e/testdata/helm-with-multiple-dependencies/Chart.yaml
  util/argo/argo.go
Labels: ready-for-review

#12401 feat: Added healthcheck for ArgoEvents EventBus CRD. #12395
  resource_customizations/argoproj.io/EventBus/health.lua
  resource_customizations/argoproj.io/EventBus/health_test.yaml
  resource_customizations/argoproj.io/EventBus/testdata/degraded.yaml
  resource_customizations/argoproj.io/EventBus/testdata/healthy.yaml
Labels: ready-for-review

#13001 fix(repo-server): completely clean up Git working directory (#3683)
  test/e2e/fixture/app/actions.go
  test/e2e/fixture/fixture.go
  test/e2e/git_submodule_test.go
  test/e2e/testdata/git-submodule/submodule-pod.yaml
  util/git/client.go
Labels: ready-for-review

#13363 fix: implement filtering on cluster `List` API endpoint
  docs/2.7-2.8.md
  docs/operator-manual/upgrading/2.7-2.8.md
  docs/operator-manual/upgrading/overview.md
  mkdocs.yml
  server/cluster/cluster.go
  server/cluster/cluster_test.go
Labels: ready-for-review

#12304 chore: code clean for hack known_types.go
  hack/known_types/main.go
Labels: ready-for-review

#12706 fix: allow sync when multiple allow windows are present
  docs/user-guide/sync_windows.md
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
Labels: ready-for-review

#13605 feat: argocd-notifications-controller log level and log format be defined with environment variables
  cmd/argocd-notification/commands/controller.go
  docs/operator-manual/argocd-cmd-params-cm.yaml
  manifests/base/notification/argocd-notifications-controller-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: ready-for-review

#13081 feat: Add controllerNamespace to .status of an application (#12964)
  assets/swagger.json
  controller/appcontroller.go
  controller/appcontroller_test.go
  manifests/core-install.yaml
  manifests/crds/application-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
Labels: apps-in-any-namespace, ready-for-review

#13661 docs: add helm values declarative syntax
  docs/user-guide/helm.md
Labels: ready-for-review

#13685 chore: clean up repeated package import
  cmd/argocd/commands/app.go
  cmd/argocd/commands/initialize/cmd.go
  cmd/argocd/commands/project.go
Labels: ready-for-review

#13469 docs: Fix titles in app deletion doc
  docs/user-guide/app_deletion.md
Labels: ready-for-review

#13520 docs: Update disaster_recovery.md to reflect quay.io as docker container registry
  docs/operator-manual/disaster_recovery.md
Labels: ready-for-review

#11846 feat: specify listen address from env / command line
  cmd/argocd-repo-server/commands/argocd_repo_server.go
  cmd/argocd-server/commands/argocd_server.go
  cmd/argocd/commands/admin/dashboard.go
  common/common.go
  docs/operator-manual/argocd-cmd-params-cm.yaml
  docs/operator-manual/server-commands/argocd-repo-server.md
  docs/operator-manual/server-commands/argocd-server.md
  docs/operator-manual/tls.md
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/base/server/argocd-server-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  server/server.go
Labels: ready-for-review

#13456 feat(appset): Add argocd.argoproj.io/application-set-name to rendered appset applications
  applicationset/controllers/applicationset_controller.go
  applicationset/controllers/applicationset_controller_test.go
  test/e2e/applicationset_test.go
  test/e2e/cluster_generator_test.go
  test/e2e/clusterdecisiongenerator_e2e_test.go
  test/e2e/matrix_e2e_test.go
  test/e2e/merge_e2e_test.go
Labels: ready-for-review

#13747 docs: fix deep links docs formatting
  docs/operator-manual/deep_links.md
Labels: ready-for-review
