Repository argoproj/argo-cd, pull requests merged in 2023-10, with the labels that each got.

#14889 docs: add `CONTRIBUTING.md` copy at repo root
  CONTRIBUTING.md
Labels: type:docs

#15808 feat: Add example to --help output for "argocd appset get"
  cmd/argocd/commands/applicationset.go
  docs/user-guide/commands/argocd_appset_get.md
Labels: hacktoberfest

#15809 feat(cli): Added example to --help output for context
  cmd/argocd/commands/context.go
  docs/user-guide/commands/argocd_context.md
Labels: hacktoberfest

#15782 feat(cli): Add example to `--help` output 1
  cmd/argocd/commands/completion.go
  cmd/argocd/commands/logout.go
  cmd/argocd/commands/relogin.go
  docs/user-guide/commands/argocd_completion.md
  docs/user-guide/commands/argocd_logout.md
  docs/user-guide/commands/argocd_relogin.md
Labels: hacktoberfest

#15814 feat(cli): Add examples to --help output for remaining "argocd account"
  cmd/argocd/commands/account.go
  docs/user-guide/commands/argocd_account.md
  docs/user-guide/commands/argocd_account_get-user-info.md
Labels: hacktoberfest

#15822 feat(cli): Add example to --help output for app actions
  cmd/argocd/commands/app_actions.go
  docs/user-guide/commands/argocd_app_actions.md
  docs/user-guide/commands/argocd_app_actions_list.md
  docs/user-guide/commands/argocd_app_actions_run.md
Labels: hacktoberfest

#15838 feat(cli): Added example to --help output for bcrypt
  cmd/argocd/commands/bcrypt.go
  docs/user-guide/commands/argocd_account.md
  docs/user-guide/commands/argocd_account_bcrypt.md
Labels: hacktoberfest

#15824 feat: Add examples to --help output for all "argocd proj" cmds
  cmd/argocd/commands/project.go
  docs/user-guide/commands/argocd_proj.md
  docs/user-guide/commands/argocd_proj_add-destination.md
  docs/user-guide/commands/argocd_proj_add-orphaned-ignore.md
  docs/user-guide/commands/argocd_proj_add-signature-key.md
  docs/user-guide/commands/argocd_proj_add-source.md
  docs/user-guide/commands/argocd_proj_allow-cluster-resource.md
  docs/user-guide/commands/argocd_proj_allow-namespace-resource.md
  docs/user-guide/commands/argocd_proj_create.md
  docs/user-guide/commands/argocd_proj_delete.md
  docs/user-guide/commands/argocd_proj_deny-cluster-resource.md
  docs/user-guide/commands/argocd_proj_deny-namespace-resource.md
  docs/user-guide/commands/argocd_proj_edit.md
  docs/user-guide/commands/argocd_proj_get.md
  docs/user-guide/commands/argocd_proj_list.md
  docs/user-guide/commands/argocd_proj_remove-destination.md
  docs/user-guide/commands/argocd_proj_remove-orphaned-ignore.md
  docs/user-guide/commands/argocd_proj_remove-signature-key.md
  docs/user-guide/commands/argocd_proj_remove-source.md
  docs/user-guide/commands/argocd_proj_set.md
Labels: hacktoberfest

#15839 feat(cli): Add example to argocd relogin command
  cmd/argocd/commands/relogin.go
  docs/user-guide/commands/argocd_relogin.md
Labels: hacktoberfest

#15873 feat: Add examples to --help output for "logs APPNAME"
  cmd/argocd/commands/app.go
  docs/user-guide/commands/argocd_app_logs.md
Labels: hacktoberfest

#15865 feat(cli): add the repo-example (#15690)
  cmd/argocd/commands/repo.go
  docs/user-guide/commands/argocd_repo.md
Labels: hacktoberfest

#15928 fix(ui): pod count tooltip fix (#15767)
  ui/src/app/applications/components/application-details/application-details.tsx
Labels: hacktoberfest

#15860 feat(cli): Add examples to projectwindows.go
  cmd/argocd/commands/projectwindows.go
  docs/user-guide/commands/argocd_proj_windows_add.md
  docs/user-guide/commands/argocd_proj_windows_update.md
Labels: hacktoberfest

#15703 chore(deps): bump Helm to 3.13.1 and Kustomize to 5.1.1
  hack/installers/checksums/helm-v3.13.1-linux-amd64.tar.gz.sha256
  hack/installers/checksums/helm-v3.13.1-linux-arm64.tar.gz.sha256
  hack/installers/checksums/helm-v3.13.1-linux-ppc64le.tar.gz.sha256
  hack/installers/checksums/helm-v3.13.1-linux-s390x.tar.gz.sha256
  hack/installers/checksums/kustomize_5.1.1_darwin_amd64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.1.1_linux_amd64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.1.1_linux_arm64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.1.1_linux_ppc64le.tar.gz.sha256
  hack/installers/checksums/kustomize_5.1.1_linux_s390x.tar.gz.sha256
  hack/tool-versions.sh
Labels: ready-for-review

#15986 feat: Add examples to --help output for "delete PROJECT ROLE-NAME"
  cmd/argocd/commands/project_role.go
  docs/user-guide/commands/argocd_proj_role_delete.md
Labels: hacktoberfest

#15866 feat(cli): add the cluster-list-example (#15690)
  cmd/argocd/commands/cluster.go
  docs/user-guide/commands/argocd_cluster_list.md
Labels: hacktoberfest

#15869 feat(cli): add the repocred-list-example (#15690)
  cmd/argocd/commands/repocreds.go
  docs/user-guide/commands/argocd_repocreds_list.md
Labels: hacktoberfest

#15862 feat: Add examples to --help output for remaining "get APPNAME"
  cmd/argocd/commands/app.go
  docs/user-guide/commands/argocd_app_get.md
Labels: hacktoberfest

#13296 fix: list manually provided external urls before generated ones
  controller/cache/info.go
  controller/cache/info_test.go
Labels: ready-for-review

#15699 docs(bounty): proposal for feature to hide annotations on secrets in UI
  docs/proposals/feature-bounties/hide-annotations.md
Labels: Open Bounty

#15962 fix(banzai/KafkaCluster): Update health.lua
  resource_customizations/kafka.banzaicloud.io/KafkaCluster/health.lua
  resource_customizations/kafka.banzaicloud.io/KafkaCluster/health_test.yaml
  resource_customizations/kafka.banzaicloud.io/KafkaCluster/testdata/healthy.yaml
Labels: ready-for-review

#15929 fix: Add timezone to projectwindows list
  cmd/argocd/commands/projectwindows.go
  docs/user-guide/commands/argocd_proj_windows_list.md
Labels: ready-for-review

#15861 feat(cli): add admin-app-example (#15690)
  cmd/argocd/commands/admin/app.go
  docs/user-guide/commands/argocd_admin_app.md
Labels: hacktoberfest

#15875 feat(cli): Add examples to `argocd proj role` cli family
  cmd/argocd/commands/project_role.go
  docs/user-guide/commands/argocd_proj_role_add-policy.md
  docs/user-guide/commands/argocd_proj_role_create-token.md
  docs/user-guide/commands/argocd_proj_role_delete-token.md
  docs/user-guide/commands/argocd_proj_role_delete.md
  docs/user-guide/commands/argocd_proj_role_get.md
  docs/user-guide/commands/argocd_proj_role_list-tokens.md
  docs/user-guide/commands/argocd_proj_role_remove-policy.md
Labels: hacktoberfest

#15983 feat: Add examples to --help output for remaining "create PROJECT ROLE-NAME"
  cmd/argocd/commands/project_role.go
  docs/user-guide/commands/argocd_proj_role_create.md
Labels: hacktoberfest

#16017 feat: Add examples to --help output for "gpg_list"
  cmd/argocd/commands/gpg.go
  docs/user-guide/commands/argocd_gpg_list.md
Labels: hacktoberfest

#16019 feat: Add examples to --help output for "get KEYID"
  cmd/argocd/commands/gpg.go
  docs/user-guide/commands/argocd_gpg_get.md
Labels: hacktoberfest

#15934 chore: fix typo in declarative tests filename
  test/e2e/declarative_test.go
Labels: ready-for-review

#16136 fix(cli): example for generate-allow-list
  cmd/argocd/commands/admin/project_allowlist.go
  docs/user-guide/commands/argocd_admin_proj_generate-allow-list.md
Labels: hacktoberfest
