Repository argoproj/argo-cd, pull requests merged in 2023-09, with the labels that each got.

#15327 fix: Cache control 404 asset requests
  server/server.go
  server/server_norace_test.go
  server/server_test.go
Labels: ready-for-review

#15362 docs: fixes a markdown typo in USERS.md
  USERS.md
Labels: ready-for-review

#15300 fix: extends clusterRole to allow cronjob and Argo workflows triggers
  manifests/cluster-rbac/server/argocd-server-clusterrole.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
Labels: cherry-pick/2.8

#15323 docs: Add KPMG to users
  USERS.md
Labels: ready-for-review

#15527 docs: Update Application Set Webhook Instructions (#13764, #11532)
  docs/operator-manual/applicationset/Generators-Git.md
  docs/operator-manual/applicationset/Generators-Pull-Request.md
Labels: documentation

#11795 docs: adds vals-operator to secrets list
  docs/operator-manual/secret-management.md
Labels: ready-for-review

#15652 fix: sidebar style
  ui/src/app/sidebar/sidebar.scss
Labels: ready-for-review
