Repository argoproj/argo-cd, pull requests merged in 2023-07, with the labels that each got.

#14218 chore: Clean up repo server imports
  reposerver/repository/repository.go
Labels: ready-for-review

#14307 fix: Change disallowed application destination message (#14284)
  test/e2e/app_management_ns_test.go
  test/e2e/app_management_test.go
  util/argo/argo.go
Labels: ready-for-review

#13729 fix: add gofmt to golangci-lint in Makefile and .github/workflows/ci-build.yaml
  .github/workflows/ci-build.yaml
  Makefile
  applicationset/generators/list.go
  applicationset/generators/pull_request_test.go
  applicationset/generators/scm_provider_test.go
  applicationset/services/pull_request/gitea_test.go
  applicationset/services/pull_request/github_test.go
  assets/embed.go
  cmd/argocd/commands/app_test.go
  cmd/argocd/commands/applicationset_test.go
  resource_customizations/embed.go
  server/badge/badge.go
  server/logout/logout.go
  test/e2e/jsonnet_test.go
  test/e2e/notification_test.go
  test/e2e/selective_sync_test.go
  ui/embed.go
  util/db/certificate.go
  util/db/helmrepository.go
  util/db/repository_legacy.go
  util/helm/client.go
  util/helm/index_test.go
  util/io/files/util.go
  util/settings/resources_filter.go
Labels: ready-for-review

#14324 docs: managedFieldsManagers example in docs needs double-quotes
  docs/user-guide/diffing.md
Labels: ready-for-review

#14377 chore: use `t.Setenv` to set env vars in tests
  applicationset/services/scm_provider/bitbucket_cloud_test.go
  controller/metrics/metrics_test.go
  controller/sharding/sharding_test.go
  controller/sharding/shuffle_test.go
  controller/state_test.go
  controller/sync_test.go
  pkg/apis/application/v1alpha1/types_test.go
  util/cert/cert_test.go
  util/config/env_test.go
  util/db/gpgkeys_test.go
  util/exec/exec_test.go
  util/git/git_test.go
  util/gpg/gpg_test.go
  util/log/logrus_test.go
  util/proxy/proxy_test.go
  util/session/sessionmanager_test.go
Labels: ready-for-review

#14199 fix: Fix pod log viewer scrollbars
  ui/src/app/applications/components/pod-logs-viewer/pod-logs-viewer.tsx
Labels: ready-for-review

#14325 chore: Replace `os.Getenv("HOME")` with `os.UserHomeDir()` (#12850)
  pkg/apis/application/v1alpha1/types.go
  util/localconfig/localconfig.go
Labels: ready-for-review

#14522 fix: 'argocd-server-tls' Secret should be loaded from informer
  util/settings/settings.go
Labels: cherry-pick/2.5, cherry-pick/2.6, cherry-pick/2.7

#13394 fix(api): return 404 when the app is not found if a project is specified (#13393)
  assets/swagger.json
  docs/developer-guide/api-docs.md
  pkg/apiclient/application/application.pb.go
  server/application/application.go
  server/application/application.proto
  server/application/application_test.go
Labels: ready-for-review

#14216 fix(ui): Fix Destination Cluster URL/Name Drop down not updating destination field (#13813)
  ui/src/app/applications/components/application-create-panel/application-create-panel.tsx
Labels: ready-for-review

#13976 fix: webhook handler fails to refresh when alternate application namespaces are configured
  util/webhook/webhook.go
  util/webhook/webhook_test.go
Labels: ready-for-review

#14680 fix: manifest generation error with null annotations (#14336)
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/invalid-metadata/bad.yaml
  reposerver/repository/testdata/nil-metadata-accessors/nil-metadata-accessors.yaml
  util/kube/kube.go
  util/kube/kube_test.go
Labels: ready-for-review

#13889 chore: clean up repeated package import
  pkg/apiclient/apiclient.go
  server/server.go
Labels: ready-for-review

#14699 fix: OCI dependency url can't contain part of repository
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/oci-dependencies/Chart.yaml
Labels: cherry-pick/2.6, cherry-pick/2.7

#14778 chore: add Autodesk to USERS.md
  USERS.md
Labels: ready-for-review

#14446 chore: Add query-scoped cluster URL in Cluster Secret E2E tests
  test/e2e/accounts_test.go
  test/e2e/deployment_test.go
  test/e2e/fixture/cluster/actions.go
  test/e2e/fixture/cluster/context.go
  test/e2e/fixture/fixture.go
Labels: ready-for-review
