Repository argoproj/argo-cd, pull requests merged in 2023-04, with the labels that each got.

#13094 docs: Add missionlane.com to USERS.md
  USERS.md
Labels: ready-for-review

#13095 docs: add KelkooGroup to users list
  USERS.md
Labels: ready-for-review

#13130 fix: --file usage is broken for 'argocd proj create' command
  cmd/util/project.go
Labels: regression, cherry-pick/2.6

#13207 docs: Fix wrong link to non existing page for applicationset reference
  docs/operator-manual/rbac.md
Labels: ready-for-review

#13189 docs: s/No supported/Not supported
  docs/user-guide/helm.md
Labels: ready-for-review

#13199 feat: add `short_sha_7` to AppSet generators (#11976)
  applicationset/generators/pull_request.go
  applicationset/generators/pull_request_test.go
  applicationset/generators/scm_provider.go
  applicationset/generators/scm_provider_test.go
  docs/operator-manual/applicationset/Generators-Pull-Request.md
  docs/operator-manual/applicationset/Generators-SCM-Provider.md
Labels: ready-for-review

#13134 chore: clean up repeated package import
  applicationset/generators/generator_spec_processor_test.go
  applicationset/generators/pull_request.go
Labels: ready-for-review

#11575 feat: Expose Helm Chart metadata in Argo CD UI (#11352)
  assets/swagger.json
  pkg/apiclient/application/application.pb.go
  pkg/apiclient/application/application.pb.gw.go
  pkg/apis/api-rules/violation_exceptions.list
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/zz_generated.deepcopy.go
  reposerver/apiclient/clientset.go
  reposerver/apiclient/mocks/RepoServerServiceClient.go
  reposerver/apiclient/repository.pb.go
  reposerver/cache/cache.go
  reposerver/repository/chart.go
  reposerver/repository/chart_test.go
  reposerver/repository/repository.go
  reposerver/repository/repository.proto
  server/application/application.go
  server/application/application.proto
  server/application/application_test.go
  ui/package.json
  ui/src/app/applications/components/application-deployment-history/revision-metadata-rows.tsx
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
  ui/src/app/shared/models.ts
  ui/src/app/shared/services/applications-service.ts
  util/helm/cmd.go
Labels: enhancement, component:ui, ready-for-review

#13184 feat: Add last sync field to application tile
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
Labels: ready-for-review
