Repository argoproj/argo-cd, pull requests merged in 2023-11, with the labels that each got.

#16192 chore: specify namespace when restarting deployments in remote e2e tests
  test/e2e/fixture/fixture.go
Labels: ready-for-review

#15432 fix(server): appset list uses argocd's namespace instead of all (#15429)
  manifests/cluster-rbac/server/argocd-server-clusterrole.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  server/applicationset/applicationset.go
  server/applicationset/applicationset_test.go
  server/server.go
Labels: ready-for-review

#16205 docs: Ensure consistent proper case of Kubernetes
  cmd/argocd/commands/project.go
  docs/developer-guide/extensions/ui-extensions.md
  docs/developer-guide/site.md
  docs/index.md
  docs/operator-manual/applicationset/Generators-Cluster-Decision-Resource.md
  docs/operator-manual/applicationset/Generators-Git.md
  docs/operator-manual/applicationset/Generators-Post-Selector.md
  docs/operator-manual/health.md
  docs/operator-manual/metrics.md
  docs/operator-manual/security.md
  docs/operator-manual/troubleshooting.md
  docs/operator-manual/upgrading/2.7-2.8.md
  docs/operator-manual/user-management/index.md
  docs/operator-manual/webhook.md
  docs/proposals/config-management-plugin-v2.md
  docs/user-guide/best_practices.md
  docs/user-guide/ci_automation.md
  docs/user-guide/commands/argocd_proj_create.md
  docs/user-guide/kustomize.md
  docs/user-guide/sync-options.md
Labels: ready-for-review

#16032 feat: add examples to --help ouput for argocd_server.go file
  cmd/argocd-server/commands/argocd_server.go
  docs/operator-manual/server-commands/argocd-server.md
Labels: hacktoberfest, ready-for-review

#16030 feat: add examples to --help output for admin.go file
  cmd/argocd/commands/admin/admin.go
  docs/user-guide/commands/argocd_admin.md
Labels: hacktoberfest

#16164 chore: Upgrade Redis to redis:7.0.14
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: ready-for-review

#16135 chore: add SECURITY-INSIGHTS.yml
  .github/workflows/release.yaml
  SECURITY-INSIGHTS.yml
  docs/developer-guide/release-process-and-cadence.md
Labels: security, github_actions

#16275 fix: failing lint and unit test
  controller/state_test.go
Labels: ready-for-review

#15188 feat: Added 'slugify' sprig function
  applicationset/controllers/applicationset_controller_test.go
  applicationset/utils/utils.go
  applicationset/utils/utils_test.go
  docs/operator-manual/applicationset/GoTemplate.md
Labels: ready-for-review

#16389 chore: Use safe example domains defined in RFC 2606
  applicationset/services/pull_request/azure_devops_test.go
  controller/cache/info_test.go
  docs/operator-manual/custom-styles.md
  docs/operator-manual/declarative-setup.md
  docs/operator-manual/high_availability.md
  docs/operator-manual/ingress.md
  docs/operator-manual/user-management/index.md
  docs/proposals/parameterized-config-management-plugins.md
  docs/proposals/project-repos-and-clusters.md
  docs/user-guide/ci_automation.md
  docs/user-guide/environment-variables.md
  docs/user-guide/external-url.md
  docs/user-guide/projects.md
  pkg/apis/application/v1alpha1/types_test.go
  resource_customizations/cert-manager.io/ClusterIssuer/testdata/degraded_acmeFailed.yaml
  resource_customizations/cert-manager.io/ClusterIssuer/testdata/healthy_registered.yaml
  resource_customizations/cert-manager.io/ClusterIssuer/testdata/progressing_noStatus.yaml
  resource_customizations/cert-manager.io/Issuer/testdata/degraded_acmeFailed.yaml
  resource_customizations/cert-manager.io/Issuer/testdata/healthy_registered.yaml
  resource_customizations/cert-manager.io/Issuer/testdata/progressing_noStatus.yaml
  resource_customizations/certmanager.k8s.io/Issuer/testdata/degraded_acmeFailed.yaml
  resource_customizations/certmanager.k8s.io/Issuer/testdata/healthy_registered.yaml
  resource_customizations/certmanager.k8s.io/Issuer/testdata/progressing_noStatus.yaml
  server/application/application_test.go
  server/applicationset/applicationset_test.go
  server/deeplinks/deeplinks_test.go
  server/notification/notification_test.go
  test/e2e/notification_test.go
  test/e2e/testdata/networking/guestbook-ui-svc-ingress.yaml
  util/dex/dex_test.go
  util/notification/settings/settings_test.go
Labels: ready-for-review

#16388 fix: set max for max cookie number to `math.MaxInt`
  util/http/http.go
Labels: ready-for-review

#12062 feat: fetch & cache groups from UserInfo Endpoint
  docs/operator-manual/user-management/index.md
  server/server.go
  server/server_test.go
  util/cache/inmemory.go
  util/oidc/oidc.go
  util/oidc/oidc_test.go
  util/settings/settings.go
  util/test/testutil.go
Labels: size/L

#16430 fix: fixed cli admin dashboard cmd
  cmd/argocd/commands/admin/admin.go
  cmd/argocd/commands/admin/dashboard.go
  cmd/argocd/commands/headless/headless.go
  docs/user-guide/commands/argocd_admin_dashboard.md
Labels: cherry-pick/2.9

#15573 feat(opentelemetry): :sparkles: support for secured OTLP endpoint and headers
  cmd/argocd-application-controller/commands/argocd_application_controller.go
  cmd/argocd-cmp-server/commands/argocd_cmp_server.go
  cmd/argocd-repo-server/commands/argocd_repo_server.go
  cmd/argocd-server/commands/argocd_server.go
  docs/operator-manual/argocd-cmd-params-cm.yaml
  docs/operator-manual/server-commands/argocd-application-controller.md
  docs/operator-manual/server-commands/argocd-repo-server.md
  docs/operator-manual/server-commands/argocd-server.md
  manifests/base/application-controller-deployment/argocd-application-controller-deployment.yaml
  manifests/base/application-controller/argocd-application-controller-statefulset.yaml
  manifests/base/repo-server/argocd-repo-server-deployment.yaml
  manifests/base/server/argocd-server-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  util/env/env.go
  util/env/env_test.go
  util/trace/trace.go
Labels: ready-for-review

#16128 feat(cli): Added example to admin-cluster.go and projectwindow.go files
  cmd/argocd/commands/admin/cluster.go
  cmd/argocd/commands/projectwindows.go
  docs/user-guide/commands/argocd_admin_cluster.md
  docs/user-guide/commands/argocd_admin_cluster_kubeconfig.md
  docs/user-guide/commands/argocd_admin_cluster_stats.md
  docs/user-guide/commands/argocd_proj_windows.md
  docs/user-guide/commands/argocd_proj_windows_add.md
  docs/user-guide/commands/argocd_proj_windows_delete.md
  docs/user-guide/commands/argocd_proj_windows_disable-manual-sync.md
  docs/user-guide/commands/argocd_proj_windows_enable-manual-sync.md
  docs/user-guide/commands/argocd_proj_windows_list.md
Labels: hacktoberfest
