Repository argoproj/argo-cd, pull requests merged in 2023-01, with the labels that each got.

#11626 fix: Applications with suspended jobs now marked "Suspended" instead of "Progressing" (#11603)
  docs/operator-manual/health.md
  docs/operator-manual/upgrading/2.5-2.6.md
  go.mod
  go.sum
Labels: cherry-pick/2.6

#11124 fix: Application's own link in UI (#11123)
  controller/appcontroller.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
  ui/src/app/applications/components/applications-list/applications-table.tsx
  ui/src/app/applications/components/utils.test.tsx
  ui/src/app/applications/components/utils.tsx
Labels: component:ui, ready-for-review

#11889 fix: remove other occurrences of externalURLS #11887
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
Labels: bug, breaking/high

#11819 fix: url parsing for non git urls: oci://, no protocol (#11816)
  ui/src/app/shared/components/urls.ts
Labels: bug, breaking/high

#11891 fix: web terminal namespace handler
  server/application/terminal.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#11617 docs: note risks of secret-injection plugins
  docs/operator-manual/secret-management.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11673 docs: no longer mark parameter overrides feature as beta
  docs/user-guide/parameters.md
Labels: type:docs

#11743 fix: upgrade qs to avoid CVE-2022-24999
  ui/yarn.lock
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11888 docs: added deep links doc
  docs/operator-manual/config-management-plugins.md
  docs/operator-manual/custom_tools.md
  docs/operator-manual/deep_links.md
  docs/operator-manual/upgrading/2.2-2.3.md
  docs/operator-manual/upgrading/2.3-2.4.md
  docs/user-guide/application_sources.md
  docs/user-guide/build-environment.md
  docs/user-guide/kustomize.md
  mkdocs.yml
Labels: cherry-pick/2.6

#11916 fix: parsed url is not exposed (#11816)
  ui/src/app/shared/components/urls.ts
Labels: bug, breaking/high, cherry-pick/2.6

#11925 chore: upgrade redis to 7.0.7 to avoid CVE-2022-3996
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11931 fix: redact secret data in deep links
  server/application/application.go
Labels: cherry-pick/2.6

#11862 fix(redis): explicit bind to redis and sentinel for IPv4 clusters (#11388)
  docs/operator-manual/high_availability.md
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: cherry-pick/2.5, cherry-pick/2.6

#11847 docs: custom health check resource group wildcard (#4212)
  docs/operator-manual/health.md
Labels: cherry-pick/2.6

#11957 chore: Add K8s v1.26, v1.25 to CI and remove v1.22
  .github/workflows/ci-build.yaml
  test/e2e/app_management_ns_test.go
  test/e2e/app_management_test.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#10915 fix: Fixed matrix requeueAfterSeconds for PR
  applicationset/generators/matrix.go
  applicationset/generators/matrix_test.go
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12015 chore: upgrade github.com/prometheus/client_golang to v1.11.1 to avoid CVE-2022-21698
  go.mod
  go.sum
Labels: cherry-pick/2.3, cherry-pick/2.4

#11616 chore: upgrade net/http2 to avoid CVE-2022-41717
  go.mod
  go.sum
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5

#11681 fix: values should always be visible, even when they are empty (#11676)
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
Labels: bug/severity:minor, cherry-pick/2.5, cherry-pick/2.6

#12059 chore: disable docker sbom and attestations
  .github/workflows/image.yaml
  .github/workflows/release.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12080 feat(UI): allow applications to declare default view preferences (#12019)
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-pod-view/pod-view.tsx
  ui/src/app/shared/models.ts
Labels: enhancement

#11946 fix: Add namespace to sub-application link URLs (#11945)
  USERS.md
  ui/src/app/applications/components/application-details/application-resource-list.tsx
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
Labels: cherry-pick/2.5, cherry-pick/2.6

#12115 fix: Support resource actions for apps in different Namespace (#12114)
  ui/src/app/shared/services/applications-service.ts
Labels: cherry-pick/2.5, cherry-pick/2.6

#11645 feat(ui): allow sorting the application list (#4060)
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/shared/components/paginate/paginate.tsx
  ui/src/app/shared/services/view-preferences-service.ts
Labels: enhancement, component:ui

#12164 fix: settings API should not fail if repo server is not available
  assets/swagger.json
  pkg/apiclient/settings/settings.pb.go
  pkg/apiclient/settings/settings.pb.gw.go
  server/settings/settings.go
  server/settings/settings.proto
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
  ui/src/app/shared/models.ts
  ui/src/app/shared/services/auth-service.ts
Labels: cherry-pick/2.6

#12179 fix: add CLI client IDs to default OIDC allowed audiences (#12170)
  docs/operator-manual/user-management/index.md
  util/oidc/provider.go
  util/settings/settings.go
  util/settings/settings_test.go
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11522 fix(health): Handling SparkApplication CRD health status if dynamic allocation is enabled (#7557)
  resource_customizations/sparkoperator.k8s.io/SparkApplication/health.lua
  resource_customizations/sparkoperator.k8s.io/SparkApplication/health_test.yaml
  resource_customizations/sparkoperator.k8s.io/SparkApplication/testdata/healthy_dynamic_alloc.yaml
  resource_customizations/sparkoperator.k8s.io/SparkApplication/testdata/healthy_dynamic_alloc_dstream.yaml
  resource_customizations/sparkoperator.k8s.io/SparkApplication/testdata/healthy_dynamic_alloc_operator_api.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#11971 fix: disable More button for multiple sources
  ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
Labels: multi-source-apps, cherry-pick/2.6

#12187 feat(security): require the `aud` claim from OIDC providers by default
  docs/operator-manual/upgrading/2.5-2.6.md
  util/session/sessionmanager_test.go
  util/settings/settings.go
Labels: cherry-pick/2.6

#11692 docs(helm): helm use to inflate chart
  docs/user-guide/helm.md
Labels: type:docs

#12234 chore: Update dex's image tag that is forgotten to be updated
  test/container/Procfile
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12139 fix: values always visible (2.5 backport)
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
Labels: cherry-pick/2.5

#12061 docs: Fix list formatting in "Resource Actions" docs page
  docs/operator-manual/resource_actions.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12037 docs: Clarify directory recursion
  docs/user-guide/directory.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12236 docs: Fix copy that refers to a different CLI flag
  docs/user-guide/helm.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6
