Repository argoproj/argo-cd, pull requests merged in 2023-06, with the labels that each got.

#13821 chore: clean up repeated package import
  cmd/argocd/commands/app_test.go
  cmd/argocd/commands/applicationset_test.go
  cmd/util/app_test.go
  controller/appcontroller_test.go
  controller/state.go
Labels: ready-for-review

#13871 fix: creds.CAPath passed helm in PullOCI (#13726)
  util/helm/cmd.go
Labels: ready-for-review

#13923 docs: add pre-release to helm tracking strategies
  docs/user-guide/tracking_strategies.md
Labels: ready-for-review

#13941 chore(deps): upgrade go to 1.20.5
  Dockerfile
  test/container/Dockerfile
  test/remote/Dockerfile
Labels: security

#13943 chore(deps): upgrade go to 1.19.10
  .github/workflows/ci-build.yaml
  .github/workflows/image.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: security

#14018 chore(deps): upgrade haproxy to 2.6.14-alpine
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: security

#14023 fix(security): upgrade go to 1.19
  .github/workflows/ci-build.yaml
  .github/workflows/image.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: security

#14048 docs: add golang upgrade note for 2.5
  docs/operator-manual/upgrading/2.4-2.5.md
Labels: security

#13980 fix(cli): support application in any namespace with `argocd app diff`(#13978)
  cmd/argocd/commands/app.go
Labels: ready-for-review

#14024 chore(deps): bump ubuntu base image version
  Dockerfile
  test/container/Dockerfile
Labels: security

#13979 feat: add health-checks for snapshot volume
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshot/health.lua
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshot/health_test.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshot/testdata/bad.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshot/testdata/good.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshot/testdata/initializing.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshotContent/health.lua
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshotContent/health_test.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshotContent/testdata/bad.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshotContent/testdata/good.yaml
  resource_customizations/snapshot.storage.k8s.io/VolumeSnapshotContent/testdata/initializing.yaml
Labels: ready-for-review

#13896 docs: Fix example domain typo
  docs/user-guide/multiple_sources.md
Labels: ready-for-review

#13434 chore: remove references to ARGOCD_REDIS
  manifests/ha/base/overlays/argocd-application-controller-statefulset.yaml
  manifests/ha/base/overlays/argocd-repo-server-deployment.yaml
  manifests/ha/base/overlays/argocd-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: ready-for-review

#12229 docs: Add documentation on background cascading deletion
  docs/operator-manual/application.yaml
  docs/user-guide/app_deletion.md
Labels: ready-for-review

#14116 chore: simplify parsing environment variables
  cmd/argocd-repo-server/commands/argocd_repo_server.go
  common/common.go
  pkg/apiclient/apiclient.go
  pkg/apis/application/v1alpha1/types.go
  server/server.go
  test/e2e/fixture/fixture.go
Labels: ready-for-review

#11984 fix(appset): regard selector in nested matrix generator's generators
  applicationset/generators/generator_spec_processor.go
  applicationset/generators/matrix.go
  applicationset/generators/merge.go
  assets/swagger.json
  docs/operator-manual/applicationset/Generators-Matrix.md
  docs/operator-manual/applicationset/Generators-Merge.md
  manifests/core-install.yaml
  manifests/crds/applicationset-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/applicationset_types.go
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/zz_generated.deepcopy.go
  test/e2e/matrix_e2e_test.go
  test/e2e/merge_e2e_test.go
Labels: ready-for-review

#13926 fix(appset): handle a race condition where RollingSync does not properly detect a successful sync
  applicationset/controllers/applicationset_controller.go
  applicationset/controllers/applicationset_controller_test.go
Labels: ready-for-review

#11538 feat(helm): helm values can be either a string or a map (#2936)
  assets/swagger.json
  cmd/argocd/commands/app.go
  cmd/argocd/commands/app_test.go
  cmd/util/app.go
  docs/operator-manual/application.yaml
  docs/user-guide/helm.md
  manifests/core-install.yaml
  manifests/crds/application-crd.yaml
  manifests/crds/applicationset-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/values.go
  pkg/apis/application/v1alpha1/values_test.go
  pkg/apis/application/v1alpha1/zz_generated.deepcopy.go
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  test/e2e/helm_test.go
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
Labels: enhancement, component:config-management

#14248 chore: just use strings.TrimSuffix
  util/git/git.go
  util/git/git_test.go
Labels: ready-for-review

#13894 docs(declarative/repo-ssh): url needs git suffix
  docs/operator-manual/declarative-setup.md
Labels: documentation

#13537 docs: Clarify "SSH known host public keys" text
  docs/operator-manual/declarative-setup.md
Labels: ready-for-review
