Repository argoproj/argo-cd, pull requests merged in 2023-03, with the labels that each got.

#11075 fix: test Procfile
  Procfile
  test/container/Procfile
Labels: ready-for-review, size/XS

#11970 docs: link directly to HA manifests
  docs/operator-manual/high_availability.md
Labels: ready-for-review

#12623 chore: Pinned container images by digest hashes in `test/container/Dockerfile` - Enhancement #12622
  test/container/Dockerfile
Labels: ready-for-review

#12640 fix: exclude test/fixtures from .dockerignore
  .dockerignore
Labels: ready-for-review

#12176 docs: Fix app patch doc
  cmd/argocd/commands/app.go
  docs/user-guide/commands/argocd_app_patch.md
Labels: ready-for-review

#12681 chore: Upgrade loader-utils to avoid CVE
  ui/yarn.lock
Labels: only-needs-a-rubber-stamp

#12664 chore: CVE 2022 24999 upgrade qs
  ui/package.json
  ui/yarn.lock
Labels: only-needs-a-rubber-stamp

#12646 chore: Upgrade json5 to avoid CVE-2022-46175
  ui/yarn.lock
Labels: only-needs-a-rubber-stamp

#10949 docs: unset finalizer before deleting an app non-cascadingly
  docs/user-guide/app_deletion.md
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12670 chore: Upgrade notifications engine.
  docs/operator-manual/notifications/services/github.md
  docs/operator-manual/upgrading/2.6-2.7.md
  go.mod
  go.sum
Labels: ready-for-review

#12555 docs: update kustomization example...
  docs/operator-manual/installation.md
Labels: ready-for-review

#12067 fix: suppress Kubernetes API deprecation warnings from application controller (#11973)
  controller/cache/cache.go
Labels: ready-for-review

#12287 fix: use field-wise templating for child matrix generators (#11661)
  applicationset/generators/generator_spec_processor.go
  applicationset/generators/generator_spec_processor_test.go
  applicationset/utils/utils.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#12631 docs: Enable dark mode and follow user preference
  mkdocs.yml
Labels: ready-for-review

#12556 feat: allow injecting the target revision over an URL parameter (#12545)
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-sync-panel/application-sync-panel.tsx
  ui/src/app/applications/components/utils.tsx
Labels: enhancement, component:ui

#12341 docs: Provide example RBAC for API server in apps-in-any-namespace
  examples/k8s-rbac/argocd-server-applications/README.md
  examples/k8s-rbac/argocd-server-applications/argocd-server-rbac-clusterrole.yaml
  examples/k8s-rbac/argocd-server-applications/argocd-server-rbac-clusterrolebinding.yaml
Labels: cherry-pick/2.6

#11109 docs: Post Selector docs moved to Generators section
  docs/operator-manual/applicationset/Generators-Post-Selector.md
  docs/operator-manual/applicationset/Generators.md
  docs/user-guide/application-set.md
  mkdocs.yml
Labels: ready-for-review, size/XS

#12768 docs: update contribution FAQ
  .github/pull_request_template.md
  docs/developer-guide/faq.md
Labels: ready-for-review

#12790 chore: upgrade redis to 7.0.9
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/container/Dockerfile
Labels: ready-for-review

#12630 docs: Replace no longer working ingress class type in ingress sample yaml
  docs/operator-manual/ingress.md
Labels: ready-for-review

#10535 docs: Add working zsh completion instructions
  cmd/argocd/commands/completion.go
  docs/user-guide/commands/argocd_completion.md
Labels: ready-for-review, size/XS

#10409 docs: cleanup HA operator manual
  docs/operator-manual/high_availability.md
Labels: ready-for-review

#12896 docs: fix version numbers in upgrade notes
  docs/operator-manual/upgrading/2.3-2.4.md
  docs/operator-manual/upgrading/2.4-2.5.md
  docs/operator-manual/upgrading/2.5-2.6.md
Labels: ready-for-review

#11491 docs: document more cluster fields
  docs/operator-manual/declarative-setup.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12299 feat: upgrade Kustomize to v5.0.1
  docs/operator-manual/declarative-setup.md
  docs/operator-manual/upgrading/2.6-2.7.md
  docs/user-guide/best_practices.md
  examples/known-hosts/kustomization.yaml
  examples/plugins/helm/kustomization.yaml
  hack/installers/checksums/kustomize_5.0.1_darwin_amd64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.0.1_darwin_arm64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.0.1_linux_amd64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.0.1_linux_arm64.tar.gz.sha256
  hack/installers/checksums/kustomize_5.0.1_linux_ppc64le.tar.gz.sha256
  hack/installers/checksums/kustomize_5.0.1_linux_s390x.tar.gz.sha256
  hack/installers/install-kustomize.sh
  hack/tool-versions.sh
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/base/redis/kustomization.yaml
  manifests/core-install.yaml
  manifests/ha/base/kustomization.yaml
  manifests/ha/base/redis-ha/kustomization.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/e2e/testdata/crashing-guestbook/kustomization.yaml
  test/e2e/testdata/hook-custom-health/kustomization.yaml
  test/e2e/testdata/https-kustomize-base/local/kustomization.yaml
  test/e2e/testdata/https-kustomize-base/remote/kustomization.yaml
  test/e2e/testdata/ssh-kustomize-base/local/kustomization.yaml
  test/e2e/testdata/ssh-kustomize-base/remote/kustomization.yaml
  test/manifests/base/kustomization.yaml
  test/manifests/cmp/kustomization.yaml
  test/manifests_test.go
Labels: ready-for-review

#11769 feat: misc UI/UX improvements
  ui/src/app/applications/components/application-conditions/application-conditions.scss
  ui/src/app/applications/components/application-conditions/application-conditions.tsx
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-details/application-resource-list.tsx
  ui/src/app/applications/components/application-node-info/application-node-info.tsx
  ui/src/app/applications/components/application-pod-view/pod-tooltip.tsx
  ui/src/app/applications/components/application-pod-view/pod-view.scss
  ui/src/app/applications/components/application-pod-view/pod-view.tsx
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.scss
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
  ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
  ui/src/app/applications/components/application-summary/application-summary.tsx
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/shared/components/events-list/events-list.tsx
  ui/src/app/shared/models.ts
Labels: enhancement, component:ui

#12923 docs: add Cloud Posse to USERS.md
  USERS.md
Labels: ready-for-review

#12420 feat(helm): set enableOCI in the UI when registering a repo
  ui/src/app/settings/components/repo-details/repo-details.tsx
  ui/src/app/settings/components/repos-list/repos-list.tsx
  ui/src/app/shared/models.ts
  ui/src/app/shared/services/repo-service.ts
Labels: enhancement, component:ui, ready-for-review

#11665 feat: Add kustomize edit set replicas (#11650)
  assets/swagger.json
  cmd/argocd/commands/app.go
  cmd/argocd/commands/app_test.go
  cmd/util/app.go
  cmd/util/app_test.go
  docs/operator-manual/application.yaml
  docs/user-guide/commands/argocd_admin_app_generate-spec.md
  docs/user-guide/commands/argocd_app_create.md
  docs/user-guide/commands/argocd_app_set.md
  docs/user-guide/commands/argocd_app_unset.md
  docs/user-guide/kustomize.md
  manifests/core-install.yaml
  manifests/crds/application-crd.yaml
  manifests/crds/applicationset-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
  pkg/apis/application/v1alpha1/zz_generated.deepcopy.go
  test/e2e/kustomize_test.go
  util/kustomize/kustomize.go
  util/kustomize/kustomize_test.go
Labels: ready-for-review

#12431 chore: clean up repeated package import
  applicationset/controllers/applicationset_controller_test.go
  cmd/argocd-applicationset-controller/commands/applicationset_controller.go
  reposerver/cache/cache_test.go
  server/applicationset/applicationset.go
  test/e2e/fixture/applicationsets/actions.go
  test/e2e/fixture/applicationsets/consequences.go
  test/e2e/fixture/applicationsets/expectation.go
  util/argo/diff/diff.go
  util/notification/argocd/service.go
Labels: ready-for-review

#11844 chore: Reused argo define api Kind and Group
  applicationset/controllers/applicationset_controller.go
  applicationset/controllers/applicationset_controller_test.go
  cmd/argocd/commands/admin/admin.go
  cmd/argocd/commands/admin/backup.go
  cmd/argocd/commands/admin/notifications.go
  cmd/argocd/commands/admin/project_allowlist.go
  cmd/argocd/commands/app_actions.go
  cmd/argocd/commands/app_test.go
  controller/health_test.go
  notification_controller/controller/controller.go
  server/application/application.go
  server/repository/repository_test.go
  test/e2e/app_management_ns_test.go
  test/e2e/app_management_test.go
  test/e2e/applicationset_test.go
  test/e2e/cluster_generator_test.go
  test/e2e/clusterdecisiongenerator_e2e_test.go
  test/e2e/matrix_e2e_test.go
  test/e2e/merge_e2e_test.go
  util/argo/audit_logger.go
Labels: ready-for-review

#12386 fix: make webhook handler work for all configured application namespaces (#11867)
  server/server.go
  util/webhook/webhook.go
  util/webhook/webhook_test.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#12995 fix: update github rsa ssh key (argo-cd#12992)
  USERS.md
  docs/operator-manual/argocd-ssh-known-hosts-cm.yaml
  docs/operator-manual/declarative-setup.md
  docs/user-guide/private-repositories.md
  hack/ssh_known_hosts
  hack/update-ssh-known-hosts.sh
  manifests/base/config/argocd-ssh-known-hosts-cm.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/certificates/ssh_known_hosts
  util/cert/cert_test.go
  util/db/certificate_test.go
Labels: ready-for-review, size/S

#12999 fix(perf): filtering process in application-list api (#12985)
  server/application/application.go
  server/application/application_test.go
  util/argo/argo.go
  util/argo/argo_test.go
Labels: ready-for-review
