Repository argoproj/argo-cd, pull requests merged in 2023-02, with the labels that each got.

#11805 fix: repo-server - prevent locked state after unclean git checkout
  go.mod
  go.sum
  util/exec/exec.go
  util/exec/exec_test.go
  util/git/client.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#11983 feat: Allow force of basic auth for HTTP repositories
  assets/swagger.json
  cmd/argocd/commands/repo.go
  cmd/argocd/commands/repocreds.go
  cmd/util/repo.go
  docs/operator-manual/argocd-repositories.yaml
  docs/user-guide/commands/argocd_admin_repo_generate-spec.md
  docs/user-guide/commands/argocd_repo_add.md
  docs/user-guide/commands/argocd_repocreds_add.md
  pkg/apiclient/repository/repository.pb.go
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
  pkg/apis/application/v1alpha1/repository_types.go
  server/repository/repository.go
  server/repository/repository.proto
  ui/src/app/settings/components/repos-list/repos-list.tsx
  ui/src/app/shared/models.ts
  ui/src/app/shared/services/repo-service.ts
  util/db/repository_secrets.go
  util/git/client.go
  util/git/creds.go
  util/git/creds_test.go
  util/git/git_test.go
  util/settings/settings.go
Labels: cherry-pick/2.6

#12252 docs: Update USERS.md with our company (Sauce Labs)
  USERS.md
Labels: ready-for-review

#12242 chore: add destination.name example
  docs/operator-manual/application.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12261 fix: return nil if reading application set was successful
  cmd/util/applicationset.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#12048 fix: disable edit button on App Details Summary and Parameters tabs multi-source apps
  ui/src/app/applications/components/application-parameters/application-parameters.tsx
  ui/src/app/applications/components/application-summary/application-summary.tsx
  ui/src/app/shared/components/editable-panel/editable-panel.tsx
Labels: multi-source-apps, cherry-pick/2.6

#12103 fix: AppSet Progressive sync fixes, docs, and logging improvements
  applicationset/controllers/applicationset_controller.go
  applicationset/controllers/applicationset_controller_test.go
  assets/swagger.json
  docs/operator-manual/applicationset/Progressive-Rollouts.md
  manifests/core-install.yaml
  manifests/crds/applicationset-crd.yaml
  manifests/ha/install.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/applicationset_types.go
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/openapi_generated.go
Labels: cherry-pick/2.6

#12218 docs: Fix heading to not include a v for the second version
  docs/operator-manual/upgrading/1.8-2.0.md
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12030 chore: upgrade cookiejar to avoid CVE-2022-25901
  ui/yarn.lock
Labels: cherry-pick/2.6

#12285 fix: don't dump SSG to server logs, change deprecation notice to v2.7
  cmd/argocd/commands/app.go
  docs/operator-manual/upgrading/2.4-2.5.md
  server/server.go
Labels: cherry-pick/2.5, cherry-pick/2.6

#12265 chore: rename 'progressive rollouts' to 'progressive syncs'
  applicationset/controllers/applicationset_controller.go
  cmd/argocd-applicationset-controller/commands/applicationset_controller.go
  docs/operator-manual/applicationset/Progressive-Syncs.md
  docs/operator-manual/argocd-cmd-params-cm.yaml
  manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  mkdocs.yml
Labels: cherry-pick/2.6

#12217 fix: multi-source app refresh (#11772)
  reposerver/cache/cache.go
  reposerver/cache/cache_test.go
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  util/webhook/webhook.go
Labels: cherry-pick/2.6

#11690 docs: update config management plugin docs
  docs/operator-manual/config-management-plugins.md
  docs/operator-manual/upgrading/2.4-2.5.md
  docs/operator-manual/upgrading/2.5-2.6.md
Labels: type:docs

#11642 fix: Use margin-left vs left to center banner
  ui/src/app/ui-banner/ui-banner.tsx
Labels: enhancement, component:ui

#12352 chore: add dist to path to use our kustomize version
  .github/workflows/ci-build.yaml
  .github/workflows/release.yaml
Labels: cherry-pick/2.3, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12267 fix: show full event message in pod event view (#12104)
  ui/src/app/shared/components/events-list/events-list.tsx
Labels: enhancement, component:ui, cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#10417 fix(security): add url validation for help chat (#9956)
  ui/src/app/ui-banner/ui-banner.tsx
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12497 docs: add missing comma in health documentation
  docs/operator-manual/health.md
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12465 docs: updated link to Jenkins and added GitHub Actions link
  docs/understand_the_basics.md
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12427 docs: add DigitalOcean to USERS.md
  USERS.md
Labels: ready-for-review

#12425 fix: setting spec.SyncPolicy crashes 'argocd appset get' output (#12424)
  cmd/argocd/commands/applicationset.go
  cmd/argocd/commands/applicationset_test.go
Labels: cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12418 feat: upgrade kubectl
  test/container/Dockerfile
Labels: ready-for-review

#12389 docs: fix typo
  docs/faq.md
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12365 docs: add groww to users
  USERS.md
Labels: ready-for-review

#12346 fix(manifests): set appset controller label `app.kubernetes.io/part-of` to `argocd`
  manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml
  manifests/base/applicationset-controller/argocd-applicationset-controller-role.yaml
  manifests/base/applicationset-controller/argocd-applicationset-controller-rolebinding.yaml
  manifests/base/applicationset-controller/argocd-applicationset-controller-sa.yaml
  manifests/base/applicationset-controller/argocd-applicationset-controller-service.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12334 chore: use http constants instead of string
  applicationset/services/pull_request/bitbucket_server_test.go
  applicationset/services/scm_provider/bitbucket_cloud.go
  applicationset/services/scm_provider/bitbucket_server_test.go
  applicationset/services/scm_provider/gitea.go
  applicationset/services/scm_provider/gitea_test.go
  applicationset/services/scm_provider/github.go
  applicationset/services/scm_provider/github_test.go
  applicationset/webhook/webhook.go
  applicationset/webhook/webhook_test.go
  controller/metrics/metrics_test.go
  hack/gen-resources/generators/repo_generator.go
  server/application/terminal_test.go
  server/badge/badge_test.go
  server/logout/logout_test.go
  server/server_norace_test.go
  server/server_test.go
  test/e2e/applicationset_test.go
  util/dex/dex.go
  util/dex/dex_test.go
  util/git/git_test.go
  util/healthz/healthz_test.go
  util/helm/client.go
  util/http/http_test.go
  util/oidc/oidc_test.go
  util/proxy/proxy_test.go
  util/swagger/swagger_test.go
  util/test/testutil.go
  util/webhook/webhook.go
  util/webhook/webhook_test.go
Labels: ready-for-review

#12293 fix(sec): upgrade mkdocs to 1.3.0
  docs/requirements.txt
Labels: ready-for-review

#12280 docs: fix a few typos and grammar mistakes
  docs/developer-guide/debugging-remote-environment.md
  docs/operator-manual/app-any-namespace.md
  docs/operator-manual/applicationset/Progressive-Syncs.md
  docs/operator-manual/deep_links.md
  docs/operator-manual/user-management/index.md
  docs/operator-manual/user-management/keycloak.md
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12203 fix: valid username in webhook URL matching regex
  util/webhook/webhook.go
  util/webhook/webhook_test.go
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12146 docs: FAQ improvements
  docs/faq.md
Labels: cherry-pick/2.4, cherry-pick/2.5, ready-for-review, cherry-pick/2.6

#12100 chore: Use topology.kubernetes.io labels for HA manifests
  manifests/ha/base/overlays/argocd-repo-server-deployment.yaml
  manifests/ha/base/overlays/argocd-server-deployment.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  resource_customizations/cassandra.rook.io/Cluster/testdata/healthy.yaml
  resource_customizations/cassandra.rook.io/Cluster/testdata/progressing.yaml
  resource_customizations/kafka.strimzi.io/KafkaConnect/testdata/degraded.yaml
  resource_customizations/kafka.strimzi.io/KafkaConnect/testdata/healthy.yaml
  resource_customizations/kafka.strimzi.io/KafkaConnect/testdata/progressing_noStatus.yaml
Labels: ready-for-review

#12499 docs: add multi source app ref in helm section
  docs/user-guide/helm.md
Labels: ready-for-review, cherry-pick/2.6

#12362 chore: use registry.k8s.io instead of k8s.gcr.io
  reposerver/repository/repository_test.go
  resource_customizations/apps/DaemonSet/actions/testdata/daemonset-restarted.yaml
  resource_customizations/apps/DaemonSet/actions/testdata/daemonset.yaml
  resource_customizations/apps/StatefulSet/actions/testdata/statefulset-restarted.yaml
  resource_customizations/apps/StatefulSet/actions/testdata/statefulset.yaml
  util/kustomize/testdata/kustomization_yaml/statefulset.yaml
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6

#12134 docs: Add help to makefile
  Makefile
Labels: ready-for-review

#12523 fix: Lint Go code(#12522)
  USERS.md
  cmd/argocd/commands/applicationset_test.go
Labels: ready-for-review

#12008 docs: fix syntax errors in the document
  SECURITY.md
  docs/developer-guide/ci.md
  docs/developer-guide/code-contributions.md
  docs/developer-guide/contributors-quickstart.md
  docs/developer-guide/releasing.md
  docs/developer-guide/running-locally.md
  docs/developer-guide/site.md
  docs/developer-guide/test-e2e.md
  docs/developer-guide/toolchain-guide.md
  docs/developer-guide/use-gitpod.md
Labels: ready-for-review

#11624 fix: fix typo in local variable name
  util/cache/cache.go
Labels: ready-for-review

#12538 fix: directory permisson of user in test/container/Dockerfile (#12537)
  test/container/Dockerfile
Labels: ready-for-review, size/XS

#12576 fix: evaluate all possible refresh reasons for multi-source apps (#12379)
  controller/appcontroller.go
  controller/appcontroller_test.go
  controller/state.go
  pkg/apis/application/v1alpha1/types.go
  test/e2e/app_multiple_sources_test.go
  test/e2e/fixture/app/actions.go
  test/e2e/fixture/app/consequences.go
Labels: cherry-pick/2.6

#12618 fix: `make verify-kube-connect` broken on arm64 architectures. #12617
  test/container/Dockerfile
Labels: ready-for-review

#12620 chore: add directories to dockerignore (used to speed up local dev)
  .dockerignore
Labels: ready-for-review

#11594 docs: add ARGOCD_API_SERVER_REPLICAS to HA docs
  docs/operator-manual/high_availability.md
Labels: ready-for-review

#12628 chore: upgrade haproxy to 2.6.9 to avoid multiple CVEs
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
Labels: cherry-pick/2.5, cherry-pick/2.6

#12627 chore: upgrade redis to 7.0.8 to avoid several CVEs
  .github/workflows/ci-build.yaml
  manifests/base/redis/argocd-redis-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  test/container/Dockerfile
Labels: cherry-pick/2.4, cherry-pick/2.5, cherry-pick/2.6
