Repository argoproj/argo-cd, pull requests merged in 2023-08, with the labels that each got.

#10700 feat: Adding kubelogin capability to argocd-k8s-auth (#9460)
  cmd/argocd-k8s-auth/commands/argocd_k8s_auth.go
  cmd/argocd-k8s-auth/commands/azure.go
  docs/operator-manual/declarative-setup.md
  go.mod
  go.sum
Labels: enhancement, ready-for-review

#14837 docs: use consistent password in plugin generator examples
  docs/operator-manual/applicationset/Generators-Plugin.md
Labels: documentation

#14537 fix: Change underscore (_) back to plus (+) to get valid SemVer when when reading tags from OCI registry
  util/helm/client.go
  util/helm/client_test.go
Labels: ready-for-review

#14913 fix(14902): Fix typo in ARGOCD_APPLICATIONSET_CONTROLLER_ALLOWED_SCM_PROVI…
  manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml
  manifests/core-install.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: ready-for-review

#15039 chore: add Carrefour Group to USERS.md
  USERS.md
Labels: ready-for-review

#15174 fix: stop creating new otel interceptor to avoid memory leak
  cmpserver/apiclient/clientset.go
  pkg/apiclient/apiclient.go
  reposerver/apiclient/clientset.go
  server/server.go
  util/grpc/trace.go
Labels: cherry-pick/2.8

#15240 chore: add Kvist to USERS.md
  USERS.md
Labels: ready-for-review
