Repository argoproj/argo-cd, pull requests merged in 2024-10, with the labels that each got.

#20096 fix: Rework git tag semver resolution (#20083)
  USERS.md
  util/git/client.go
  util/git/client_test.go
  util/git/git_test.go
Labels: ready-for-review

#20040 fix: allow pipes to be present in git username
  util/git/client.go
  util/git/client_test.go
Labels: ready-for-review

#17222 docs: document server side pagination proposal
  docs/proposals/server-side-pagination.md
Labels: component:docs

#19655 chore(deps): upgrade `argo-ui`, including breaking changes
  ui/src/app/applications/components/application-deployment-history/application-deployment-history.tsx
  ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
  ui/src/app/settings/components/cluster-details/cluster-details.tsx
  ui/yarn.lock
Labels: dependencies, component:ui, javascript

#20043 fix: check err before use schedule and duration
  cmd/argocd/commands/app.go
  cmd/argocd/commands/projectwindows.go
  controller/appcontroller.go
  controller/sync.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
  server/application/application.go
  server/project/project.go
Labels: ready-for-review
