Repository argoproj/argo-cd, pull requests merged in 2024-04, with the labels that each got.

#14617 feat(server): Add maxPodLogsToRender setting (#9131)
  docs/operator-manual/argocd-cm.yaml
  server/application/application.go
  server/application/application_test.go
  util/settings/settings.go
Labels: enhancement, ready-for-review

#10494 docs: add argocd-secret-replacer
  docs/operator-manual/secret-management.md
Labels: lifecycle/rotten, ready-for-review

#10955 fix: UI Error caused by missing RBAC Permission
  ui/src/app/applications/components/resource-details/resource-details.tsx
Labels: cherry-pick/2.4, cherry-pick/2.5
