Repository argoproj/argo-cd, pull requests merged in 2024-03, with the labels that each got.

#14294 fix(grpcproxy): parse headers contain colon (#13274)
  pkg/apiclient/apiclient_test.go
  pkg/apiclient/grpcproxy.go
Labels: ready-for-review

#8030 docs: Add note in installation step 1 with argocd cli
  docs/getting_started.md
Labels: lifecycle/rotten

#9487 docs(dex): Add documentation for fetching google transitive groups
  docs/operator-manual/user-management/google.md
Labels: documentation, lifecycle/rotten

#17425 feat: add cli commands to create/set/unset/edit sources for multi-source application
  cmd/argocd/commands/app.go
  cmd/util/app.go
  cmd/util/app_test.go
  docs/user-guide/commands/argocd_app.md
  docs/user-guide/commands/argocd_app_create.md
  docs/user-guide/commands/argocd_app_remove-source.md
  docs/user-guide/commands/argocd_app_set.md
  docs/user-guide/commands/argocd_app_unset.md
  pkg/apis/application/v1alpha1/types.go
  server/repository/repository_test.go
  util/notification/expression/repo/repo.go
Labels: component:cli, multi-source-apps

#17395 feat(UI): Added link for docs to add clusters
  ui/src/app/settings/components/clusters-list/cluster-list.scss
  ui/src/app/settings/components/clusters-list/clusters-list.tsx
Labels: component:ui
