Repository argoproj/argo-cd, pull requests merged in 2024-05, with the labels that each got.

#16715 feat: implement keda health-checks
  resource_customizations/keda.sh/ScaledObject/health.lua
  resource_customizations/keda.sh/ScaledObject/health_test.yaml
  resource_customizations/keda.sh/ScaledObject/testdata/keda-degraded-1.yaml
  resource_customizations/keda.sh/ScaledObject/testdata/keda-degraded.yaml
  resource_customizations/keda.sh/ScaledObject/testdata/keda-healthy.yaml
  resource_customizations/keda.sh/ScaledObject/testdata/keda-progressing.yaml
  resource_customizations/keda.sh/ScaledObject/testdata/keda-suspended.yaml
Labels: ready-for-review

#18174 chore: Improve appcontroller logs further - Closes [#18113]
  controller/appcontroller.go
Labels: ready-for-review

#12667 fix(controller): copy visited map (#11699)
  controller/cache/cache.go
  controller/cache/cache_test.go
Labels: ready-for-review

#18257 docs: expand appset post selector examples
  docs/operator-manual/applicationset/Generators-Post-Selector.md
Labels: documentation

#18243 fix(ui): Add title for full content without clicking (issue #17600)
  ui/src/app/applications/components/application-details/application-resource-list.tsx
Labels: component:ui

#14823 docs: removing strikeout as it was populating special character
  docs/operator-manual/upgrading/2.4-2.5.md
Labels: documentation

#17766 docs: Update ingress.md so it works properly with Istio service mesh
  docs/operator-manual/ingress.md
Labels: type:docs

#13203 feat: removed legacy app tracking label
  util/argo/resource_tracking.go
  util/kube/kube.go
  util/kube/kube_test.go
  util/settings/settings.go
Labels: ready-for-review
