Repository argoproj/argo-cd, pull requests merged in 2025-05, with the labels that each got.

#20886 fix(ui): Added tooltip for buttons in narrow window
  ui/src/app/applications/components/applications-list/applications-list.scss
  ui/src/app/applications/components/applications-list/applications-list.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.scss
  ui/src/app/applications/components/applications-list/applications-tiles.tsx
Labels: ready-for-review

#21552 feat(health): add kyverno Policy resource customization
  resource_customizations/kyverno.io/Policy/health.lua
  resource_customizations/kyverno.io/Policy/health_test.yaml
  resource_customizations/kyverno.io/Policy/testdata/healthy.yaml
  resource_customizations/kyverno.io/Policy/testdata/progressing.yaml
Labels: ready-for-review, component:health-check

#20766 feat(AppProject): Add sync window description
  assets/swagger.json
  cmd/argocd/commands/app.go
  cmd/argocd/commands/projectwindows.go
  docs/user-guide/commands/argocd_proj_windows.md
  docs/user-guide/commands/argocd_proj_windows_add.md
  docs/user-guide/commands/argocd_proj_windows_delete.md
  docs/user-guide/commands/argocd_proj_windows_disable-manual-sync.md
  docs/user-guide/commands/argocd_proj_windows_enable-manual-sync.md
  docs/user-guide/commands/argocd_proj_windows_update.md
  manifests/core-install-with-hydrator.yaml
  manifests/core-install.yaml
  manifests/crds/appproject-crd.yaml
  manifests/ha/install-with-hydrator.yaml
  manifests/ha/install.yaml
  manifests/install-with-hydrator.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
  ui/src/app/settings/components/project-details/project-details.scss
  ui/src/app/settings/components/project-details/project-details.tsx
  ui/src/app/settings/components/project-sync-windows-edit-panel/project-sync-windows-edit-panel.tsx
  ui/src/app/shared/models.ts
Labels: ready-for-review

#22746 fix: do not normalize resource tracking on live crds (#22722) - cherrypick 2.14
  util/argo/resource_tracking.go
  util/argo/resource_tracking_test.go
Labels: ready-for-review

#21537 fix(repo-server): When using custom kustomize versions, obtain the correct path (#21449)
  util/kustomize/kustomize.go
  util/kustomize/kustomize_test.go
Labels: ready-for-review

#22254 fix: prevent rootpath duplication in OIDC redirect URLs, fixes #21857 #20790 #12195
  server/rootpath_test.go
  server/server.go
Labels: ready-for-review

#21782 feat(ui): support delete all expired token in project roles
  ui/src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
  ui/src/app/settings/components/project-role-jwt-tokens/project-role-jwt-tokens.scss
  ui/src/app/settings/components/project-role-jwt-tokens/project-role-jwt-tokens.tsx
  ui/src/app/shared/components/progress/__snapshots__/progress-popup.test.tsx.snap
  ui/src/app/shared/components/progress/progress-popup.scss
  ui/src/app/shared/components/progress/progress-popup.tsx
Labels: ready-for-review

#20783 feat(ui): Added Sort by age in Pod-view
  ui/src/app/applications/components/application-pod-view/pod-view.tsx
  ui/src/app/shared/services/view-preferences-service.ts
Labels: ready-for-review

#20812 feat(ui): Added toggle for fullname of resources in application-details-tree.
  ui/src/app/applications/components/application-details/application-details.tsx
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.scss
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
  ui/src/app/applications/components/applications-list/applications-tiles.scss
Labels: ready-for-review

#20216 chore(repo-server): unify semver resolution in new versions subpackage
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  util/git/client.go
  util/git/client_test.go
  util/helm/client.go
  util/helm/client_test.go
  util/helm/index.go
  util/helm/index_test.go
  util/helm/mocks/Client.go
  util/helm/tags.go
  util/helm/tags_test.go
  util/versions/tags.go
  util/versions/tags_test.go
  util/versions/version.go
  util/versions/version_test.go
Labels: ready-for-review

#22878 fix: Race condition in `nativeGitClient.LsFiles` (issue #21754)
  util/git/client.go
  util/git/client_test.go
Labels: ready-for-review

#18283 fix: HA proxy memory runaway on certain rpm based distro's -> Setting maxconn in haproxy config (#15319)
  manifests/ha/base/redis-ha/chart/upstream.yaml
  manifests/ha/base/redis-ha/chart/values.yaml
  manifests/ha/install-with-hydrator.yaml
  manifests/ha/install.yaml
  manifests/ha/namespace-install-with-hydrator.yaml
  manifests/ha/namespace-install.yaml
Labels: ready-for-review

#22197 docs: Add missing URL configuration for Google Groups SSO with Dex
  docs/operator-manual/user-management/google.md
Labels: ready-for-review

#21148 feat: support gitea PR labels filter in applicationset PR generator (#21115)
  applicationset/generators/pull_request.go
  applicationset/services/pull_request/gitea.go
  applicationset/services/pull_request/gitea_test.go
  assets/swagger.json
  manifests/core-install-with-hydrator.yaml
  manifests/core-install.yaml
  manifests/crds/applicationset-crd.yaml
  manifests/ha/install-with-hydrator.yaml
  manifests/ha/install.yaml
  manifests/install-with-hydrator.yaml
  manifests/install.yaml
  pkg/apis/application/v1alpha1/applicationset_types.go
  pkg/apis/application/v1alpha1/generated.pb.go
  pkg/apis/application/v1alpha1/generated.proto
  pkg/apis/application/v1alpha1/zz_generated.deepcopy.go
Labels: ready-for-review

#20996 feat(ui): add keydown event to the pod dropdown menu
  ui/src/app/applications/components/application-details/application-details.scss
  ui/src/app/applications/components/utils.tsx
Labels: ready-for-review

#22036 fix(appcontroller): if a history limit is negative, automatically converted to 0
  controller/state_test.go
  pkg/apis/application/v1alpha1/types.go
  pkg/apis/application/v1alpha1/types_test.go
Labels: ready-for-review

#21576 feat(ui): disable select not running pod and bring back arrow to selected pod
  ui/src/app/applications/components/pod-terminal-viewer/pod-terminal-viewer.scss
  ui/src/app/applications/components/pod-terminal-viewer/pod-terminal-viewer.tsx
Labels: ready-for-review

#21012 fix(ui): Replace current spinning webfont icon with svg icons
  ui/src/app/applications/components/__snapshots__/utils.test.tsx.snap
  ui/src/app/applications/components/application-resource-tree/application-resource-tree.scss
  ui/src/app/applications/components/utils.scss
  ui/src/app/applications/components/utils.test.tsx
  ui/src/app/applications/components/utils.tsx
  ui/src/app/shared/components/spinner.tsx
Labels: ready-for-review

#22493 feat: Implement grafana-operator Dashboard and Folder CRD health checks
  resource_customizations/grafana.integreatly.org/GrafanaDashboard/health.lua
  resource_customizations/grafana.integreatly.org/GrafanaDashboard/health_test.yaml
  resource_customizations/grafana.integreatly.org/GrafanaDashboard/testdata/degraded.yaml
  resource_customizations/grafana.integreatly.org/GrafanaDashboard/testdata/healthy.yaml
  resource_customizations/grafana.integreatly.org/GrafanaDashboard/testdata/progressing.yaml
  resource_customizations/grafana.integreatly.org/GrafanaFolder/health.lua
  resource_customizations/grafana.integreatly.org/GrafanaFolder/health_test.yaml
  resource_customizations/grafana.integreatly.org/GrafanaFolder/testdata/degraded.yaml
  resource_customizations/grafana.integreatly.org/GrafanaFolder/testdata/healthy.yaml
  resource_customizations/grafana.integreatly.org/GrafanaFolder/testdata/progressing.yaml
Labels: component:health-check

#21873 docs: detailed valid states for pullRequestState
  assets/swagger.json
  docs/operator-manual/applicationset/Generators-Pull-Request.md
Labels: ready-for-review

#21260 chore: Improve checkResourceStatus readability
  cmd/argocd/commands/app.go
Labels: ready-for-review

#22709 chore(deps): resolve CVE GO-2025-3540, GO-2025-3503, GO-2025-3487 within 2.14.10
  go.mod
  go.sum
  server/server_test.go
Labels: ready-for-review

#21442 chore(logs): standardize application logging (#20731)
  applicationset/controllers/applicationset_controller.go
  applicationset/controllers/applicationset_controller_test.go
  controller/appcontroller.go
  controller/health.go
  controller/hydrator/hydrator.go
  controller/state.go
  controller/sync.go
  controller/utils/log.go
  docs/operator-manual/security.md
  server/application/application.go
  server/application/broadcaster.go
  util/app/log/log.go
Labels: ready-for-review

#22596 feat: Contour HTTPProxy health check support for issue # 22504
  resource_customizations/projectcontour.io/HTTPProxy/health.lua
  resource_customizations/projectcontour.io/HTTPProxy/health_test.yaml
  resource_customizations/projectcontour.io/HTTPProxy/testdata/degraded.yaml
  resource_customizations/projectcontour.io/HTTPProxy/testdata/healthy.yaml
  resource_customizations/projectcontour.io/HTTPProxy/testdata/not_reconciled.yaml
  resource_customizations/projectcontour.io/HTTPProxy/testdata/progressing.yaml
Labels: component:health-check

#22066 feat(health): add Rabbitmq topology resource customizations
  resource_customizations/rabbitmq.com/Binding/health.lua
  resource_customizations/rabbitmq.com/Binding/health_test.yaml
  resource_customizations/rabbitmq.com/Binding/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Binding/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Binding/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/Exchange/health.lua
  resource_customizations/rabbitmq.com/Exchange/health_test.yaml
  resource_customizations/rabbitmq.com/Exchange/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Exchange/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Exchange/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/Permission/health.lua
  resource_customizations/rabbitmq.com/Permission/health_test.yaml
  resource_customizations/rabbitmq.com/Permission/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Permission/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Permission/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/Policy/health.lua
  resource_customizations/rabbitmq.com/Policy/health_test.yaml
  resource_customizations/rabbitmq.com/Policy/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Policy/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Policy/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/Queue/health.lua
  resource_customizations/rabbitmq.com/Queue/health_test.yaml
  resource_customizations/rabbitmq.com/Queue/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Queue/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Queue/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/Shovel/health.lua
  resource_customizations/rabbitmq.com/Shovel/health_test.yaml
  resource_customizations/rabbitmq.com/Shovel/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Shovel/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Shovel/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/User/health.lua
  resource_customizations/rabbitmq.com/User/health_test.yaml
  resource_customizations/rabbitmq.com/User/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/User/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/User/testdata/unknown.yaml
  resource_customizations/rabbitmq.com/Vhost/health.lua
  resource_customizations/rabbitmq.com/Vhost/health_test.yaml
  resource_customizations/rabbitmq.com/Vhost/testdata/degraded.yaml
  resource_customizations/rabbitmq.com/Vhost/testdata/healthy.yaml
  resource_customizations/rabbitmq.com/Vhost/testdata/unknown.yaml
Labels: component:health-check

#23156 feat(health): OpenTelemetryCollector CRD Healthcheck
  resource_customizations/opentelemetry.io/OpenTelemetryCollector/health.lua
  resource_customizations/opentelemetry.io/OpenTelemetryCollector/health_test.yaml
  resource_customizations/opentelemetry.io/OpenTelemetryCollector/testdata/degraded.yaml
  resource_customizations/opentelemetry.io/OpenTelemetryCollector/testdata/healthy.yaml
  resource_customizations/opentelemetry.io/OpenTelemetryCollector/testdata/progressing.yaml
Labels: component:health-check

#21896 feat: Implement spinkube SpinApp CRD health checks
  resource_customizations/core.spinkube.dev/SpinApp/health.lua
  resource_customizations/core.spinkube.dev/SpinApp/health_test.yaml
  resource_customizations/core.spinkube.dev/SpinApp/testdata/degraded.yaml
  resource_customizations/core.spinkube.dev/SpinApp/testdata/healthy.yaml
  resource_customizations/core.spinkube.dev/SpinApp/testdata/no-status.yaml
  resource_customizations/core.spinkube.dev/SpinApp/testdata/progressing.yaml
Labels: component:health-check
