Repository argoproj/argo-cd, pull requests merged in 2025-06, with the labels that each got.

#19829 feat(ui): allows more convenient sorting of repository.
  ui/src/app/settings/components/repos-list/repos-list.scss
  ui/src/app/settings/components/repos-list/repos-list.tsx
Labels: component:ui, ready-for-review

#22043 fix: do not fail on manifest-like yaml files - fixes #21934
  docs/user-guide/directory.md
  reposerver/repository/repository.go
  reposerver/repository/repository_test.go
  reposerver/repository/testdata/invalid-manifests-skipped/bad.yaml
Labels: ready-for-review

#22855 feat: Implement healthcheck gateway api (#20986)
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/health.lua
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/health_test.yaml
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/testdata/degraded_accepted.yaml
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/testdata/degraded_no_message.yaml
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/testdata/degraded_no_parent_name.yaml
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/testdata/degraded_resolved_refs.yaml
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/testdata/healthy.yaml
  resource_customizations/gateway.networking.k8s.io/GRPCRoute/testdata/progressing.yaml
  resource_customizations/gateway.networking.k8s.io/Gateway/health.lua
  resource_customizations/gateway.networking.k8s.io/Gateway/health_test.yaml
  resource_customizations/gateway.networking.k8s.io/Gateway/testdata/degraded_accepted.yaml
  resource_customizations/gateway.networking.k8s.io/Gateway/testdata/degraded_resolved_refs.yaml
  resource_customizations/gateway.networking.k8s.io/Gateway/testdata/healthy.yaml
  resource_customizations/gateway.networking.k8s.io/Gateway/testdata/listener_degraded.yaml
  resource_customizations/gateway.networking.k8s.io/Gateway/testdata/progressing.yaml
  resource_customizations/gateway.networking.k8s.io/HTTPRoute/health.lua
  resource_customizations/gateway.networking.k8s.io/HTTPRoute/health_test.yaml
  resource_customizations/gateway.networking.k8s.io/HTTPRoute/testdata/degraded_accepted.yaml
  resource_customizations/gateway.networking.k8s.io/HTTPRoute/testdata/degraded_resolved_refs.yaml
  resource_customizations/gateway.networking.k8s.io/HTTPRoute/testdata/healthy.yaml
  resource_customizations/gateway.networking.k8s.io/HTTPRoute/testdata/progressing.yaml
Labels: component:health-check

#23173 feat(health-check): add resource_customizations for ocs.openshift.io
  resource_customizations/ocs.openshift.io/StorageCluster/health.lua
  resource_customizations/ocs.openshift.io/StorageCluster/health_test.yaml
  resource_customizations/ocs.openshift.io/StorageCluster/testdata/degraded.yaml
  resource_customizations/ocs.openshift.io/StorageCluster/testdata/healthy_available.yaml
  resource_customizations/ocs.openshift.io/StorageCluster/testdata/healthy_upgradeable.yaml
  resource_customizations/ocs.openshift.io/StorageCluster/testdata/progressing.yaml
Labels: ready-for-review

#22028 feat(health): add Logstash resource customization
  resource_customizations/logstash.k8s.elastic.co/Logstash/health.lua
  resource_customizations/logstash.k8s.elastic.co/Logstash/health_test.yaml
  resource_customizations/logstash.k8s.elastic.co/Logstash/testdata/green.yaml
  resource_customizations/logstash.k8s.elastic.co/Logstash/testdata/red.yaml
  resource_customizations/logstash.k8s.elastic.co/Logstash/testdata/unknown.yaml
  resource_customizations/logstash.k8s.elastic.co/Logstash/testdata/yellow.yaml
Labels: component:health-check

#21729 chore: move OIDC PKCE support from UI to backend
  docs/assets/keycloak-configure-client-pkce.png
  docs/operator-manual/upgrading/3.0-3.1.md
  docs/operator-manual/user-management/index.md
  docs/operator-manual/user-management/keycloak.md
  server/server_test.go
  ui/package.json
  ui/src/app/app.tsx
  ui/src/app/login/components/login.tsx
  ui/src/app/login/components/pkce-verify.scss
  ui/src/app/login/components/pkce-verify.tsx
  ui/src/app/login/components/utils.ts
  ui/src/app/shared/models.ts
  ui/yarn.lock
  util/dex/config.go
  util/oidc/oidc.go
  util/oidc/oidc_test.go
  util/session/sessionmanager_test.go
  util/settings/settings.go
  util/test/testutil.go
Labels: ready-for-review

#23343 feat: Export metrics to track number of users (#20801)
  docs/operator-manual/metrics.md
  server/metrics/metrics.go
  server/server.go
  server/session/session.go
  util/session/sessionmanager.go
Labels: ready-for-review
