Repository argoproj/argo-cd, pull requests merged in 2025-09, with the labels that each got.

#23558 feat(health-check): Add resource_customizations for game.kruise.io (new)
  resource_customizations/game.kruise.io/GameServer/health.lua
  resource_customizations/game.kruise.io/GameServer/health_test.yaml
  resource_customizations/game.kruise.io/GameServer/testdata/degraded.yaml
  resource_customizations/game.kruise.io/GameServer/testdata/healthy.yaml
  resource_customizations/game.kruise.io/GameServer/testdata/progressing.yaml
  resource_customizations/game.kruise.io/GameServer/testdata/unknown.yaml
  resource_customizations/game.kruise.io/GameServerSet/health.lua
  resource_customizations/game.kruise.io/GameServerSet/health_test.yaml
  resource_customizations/game.kruise.io/GameServerSet/testdata/healthy.yaml
  resource_customizations/game.kruise.io/GameServerSet/testdata/progressing-init.yaml
  resource_customizations/game.kruise.io/GameServerSet/testdata/progressing.yaml
  resource_customizations/game.kruise.io/GameServerSet/testdata/suspended-partition.yaml
  resource_customizations/game.kruise.io/GameServerSet/testdata/suspended-paused.yaml
Labels: component:health-check

#23659 fix(project): Do not block project update when a cluster referenced in an App doesn't exist
  server/project/project.go
  server/project/project_test.go
Labels: ready-for-review

#24525 ci(release): only set latest release in github when latest
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: cherry-pick/3.0, cherry-pick/3.1, cherry-pick/2.14

#24726 fix(health): typo in PromotionStrategy health.lua
  resource_customizations/promoter.argoproj.io/PromotionStrategy/health.lua
  resource_customizations/promoter.argoproj.io/PromotionStrategy/health_test.yaml
  resource_customizations/promoter.argoproj.io/PromotionStrategy/testdata/different-proposed-commits.yaml
Labels: cherry-pick/3.2

#24669 chore: Add appkey and error fields in appcontroller (#24668)
  controller/appcontroller.go
  controller/appcontroller_test.go
Labels: ready-for-review
